"""Language facts for Braino: handwriting, cursive, vocabulary, jokes, and self.

Aimed squarely at a five to eight year old talking to a small speaker. The
original game shipped a two hundred fifty word GRE list ("didactic",
"consternation"); that vocabulary is a decade too old for this device, so the
list is gone and the *skill* is kept: what words mean, what kind of word a word
is, opposites, synonyms, rhyme, syllables, plurals.

Spelling here teaches the concepts only - what a vowel is, how many letters a
short word has, what rhyming means - with a handful of worked examples. The
per-word spelling drill is generated elsewhere and would only duplicate here.
"""
from . import Fact, report

HAND = "handwriting & spelling"
CURSIVE = "cursive writing"
VOCAB = "vocabulary"
JOKES = "jokes & fun"
ME = "about me"


def f(topic, answer, train, evalq):
    """Small constructor so the tables below stay readable."""
    return Fact(topic=topic, train=list(train), answer=answer, evalq=list(evalq))


def jk(subject, answer):
    """A joke keyed to one distinct subject, so 'a joke about X' finds it."""
    return Fact(
        topic=JOKES,
        train=[
            f"tell me a joke about {subject}",
            f"do you know a joke about {subject}",
            f"say a funny joke about {subject}",
            f"i want a {subject} joke",
        ],
        evalq=[f"have you got a joke about {subject}"],
        answer=answer,
    )


# --------------------------------------------------------------------------
# handwriting & spelling
# --------------------------------------------------------------------------

def _handwriting():
    return [
        f(HAND,
          "The alphabet has twenty-six letters. It starts at a and ends at z.",
          ["how many letters are in the alphabet",
           "how many letters in the alphabet",
           "how many letters are there altogether",
           "what is the number of letters in the alphabet"],
          ["how many letters does the alphabet have"]),
        f(HAND,
          "The alphabet is all the letters we use to build words. It goes a b c "
          "d e f g and keeps going all the way to z.",
          ["what is the alphabet",
           "what does alphabet mean",
           "tell me about the alphabet",
           "what is an alphabet"],
          ["can you explain the alphabet to me"]),
        f(HAND,
          "The first letter of the alphabet is a. The last letter is z.",
          ["what is the first letter of the alphabet",
           "which letter comes first in the alphabet",
           "what letter does the alphabet start with",
           "what is the last letter of the alphabet"],
          ["which letter is at the beginning of the alphabet"]),
        f(HAND,
          "The five vowels are a, e, i, o, and u. Almost every word needs at "
          "least one vowel in it.",
          ["what is a vowel",
           "what are the vowels",
           "tell me the vowels",
           "which letters are vowels"],
          ["can you say all the vowels"]),
        f(HAND,
          "There are five vowels. They are a, e, i, o, and u.",
          ["how many vowels are there",
           "how many vowels are in the alphabet",
           "what is the number of vowels",
           "how many vowel letters are there"],
          ["how many vowels does english have"]),
        f(HAND,
          "A consonant is any letter that is not a vowel, like b, c, d, and f. "
          "There are twenty-one consonants.",
          ["what is a consonant",
           "what does consonant mean",
           "tell me what a consonant is",
           "how many consonants are there"],
          ["can you explain consonants"]),
        f(HAND,
          "The letter y is a sneaky one. In yellow it acts like a consonant, but "
          "in happy and sky it does the job of a vowel.",
          ["is y a vowel",
           "why is y sometimes a vowel",
           "is the letter y a vowel or a consonant",
           "tell me about the letter y"],
          ["what kind of letter is y"]),
        f(HAND,
          "Uppercase letters are the big ones, like A, B, and C. We use them to "
          "start a sentence and to start a name.",
          ["what is an uppercase letter",
           "what does uppercase mean",
           "what is a capital letter",
           "what are big letters called"],
          ["can you explain capital letters"]),
        f(HAND,
          "Lowercase letters are the small ones, like a, b, and c. Most of the "
          "letters in a word are lowercase.",
          ["what is a lowercase letter",
           "what does lowercase mean",
           "what are small letters called",
           "tell me about lowercase letters"],
          ["can you explain lowercase letters"]),
        f(HAND,
          "Every letter has two shapes. Big A is uppercase and little a is "
          "lowercase. They say the same sound.",
          ["what is the difference between uppercase and lowercase",
           "how is a capital letter different from a small letter",
           "why do letters have two shapes",
           "are big letters and small letters the same"],
          ["what makes uppercase different from lowercase"]),
        f(HAND,
          "Names always start with a capital letter. Your name, your street, and "
          "the days of the week all begin big.",
          ["when do i use a capital letter",
           "when should i use capital letters",
           "which words start with a capital letter",
           "do names start with a capital letter"],
          ["when do i need a big letter"]),
        f(HAND,
          "A letter is one shape like m. A word is a group of letters that means "
          "something, like mom.",
          ["what is the difference between a letter and a word",
           "is a letter the same as a word",
           "what is a letter",
           "how is a word different from a letter"],
          ["can you tell me what a letter is"]),
        f(HAND,
          "The alphabet song sings the letters in order. Singing it is a great "
          "way to remember which letter comes next.",
          ["what is the alphabet song",
           "why do we sing the alphabet",
           "how does the alphabet song help me",
           "tell me about the abc song"],
          ["what is the abc song for"]),
        f(HAND,
          "The letter after m is n. The alphabet goes k l m n o p.",
          ["what letter comes after m",
           "which letter is after m",
           "what is the next letter after m",
           "what letter follows m"],
          ["what comes right after the letter m"]),
        f(HAND,
          "The letter before f is e. The alphabet goes c d e f g.",
          ["what letter comes before f",
           "which letter is before f",
           "what letter is in front of f",
           "what comes just before f"],
          ["which letter goes right before f"]),
        f(HAND,
          "The letter b says buh, like in ball and bed.",
          ["what sound does b make",
           "what sound does the letter b make",
           "how do you say the letter b sound",
           "what noise does b make"],
          ["what is the sound of the letter b"]),
        f(HAND,
          "The letter m says mmm, like in moon and mop. You keep your lips closed.",
          ["what sound does m make",
           "what sound does the letter m make",
           "how do you say the m sound",
           "what noise does m make"],
          ["what is the sound of the letter m"]),
        f(HAND,
          "The letter s says sss, like a snake. You hear it in sun and sock.",
          ["what sound does s make",
           "what sound does the letter s make",
           "how do you say the s sound",
           "what noise does s make"],
          ["what is the sound of the letter s"]),
        f(HAND,
          "The letter c has two sounds. It says kuh in cat and sss in city.",
          ["what sound does c make",
           "what sound does the letter c make",
           "why does c have two sounds",
           "how do you say the c sound"],
          ["what is the sound of the letter c"]),
        f(HAND,
          "The letter g has two sounds. It says guh in goat and juh in giraffe.",
          ["what sound does g make",
           "what sound does the letter g make",
           "why does g have two sounds",
           "how do you say the g sound"],
          ["what is the sound of the letter g"]),
        f(HAND,
          "When s and h stand together they say shhh, like in ship and shell.",
          ["what sound does sh make",
           "what does s h say together",
           "how do you say the sh sound",
           "what noise do s and h make together"],
          ["what is the sh sound"]),
        f(HAND,
          "When c and h stand together they say ch, like in chip and cheese.",
          ["what sound does ch make",
           "what do c and h say together",
           "how do you say the ch sound",
           "what noise do c and h make together"],
          ["what is the ch sound"]),
        f(HAND,
          "When t and h stand together they say th, like in this and thumb. Your "
          "tongue peeks out between your teeth.",
          ["what sound does th make",
           "what do t and h say together",
           "how do you say the th sound",
           "what noise do t and h make together"],
          ["what is the th sound"]),
        f(HAND,
          "Hold your pencil with your thumb and your pointer finger, and rest it "
          "on your middle finger. That is called a tripod grip.",
          ["how do i hold a pencil",
           "how should i hold my pencil",
           "what is the right way to hold a pencil",
           "how do you hold a pencil properly"],
          ["what is the best way to grip a pencil"]),
        f(HAND,
          "Hold the pencil gently, about one finger above the sharp end. A tight "
          "squeeze makes your hand tired fast.",
          ["where should i hold the pencil",
           "should i hold my pencil tight",
           "why does my hand hurt when i write",
           "how hard should i squeeze my pencil"],
          ["how tightly do i hold a pencil"]),
        f(HAND,
          "Left handed writers hold a pencil the same way, just with the other "
          "hand. Tilt the paper the other way so your hand does not smudge.",
          ["how do left handed people write",
           "i am left handed how do i write",
           "is it okay to write with my left hand",
           "how should a left handed person hold a pencil"],
          ["what should left handed writers do"]),
        f(HAND,
          "Handwriting is writing letters by hand with a pencil or a pen instead "
          "of typing them.",
          ["what is handwriting",
           "what does handwriting mean",
           "tell me about handwriting",
           "what do we call writing by hand"],
          ["can you explain handwriting"]),
        f(HAND,
          "Lines on the paper show you where letters sit. Tall letters touch the "
          "top line and short letters stay small in the middle.",
          ["why do we write on lines",
           "what are the lines on writing paper for",
           "why does my paper have lines",
           "how do lines help my writing"],
          ["what do the lines on the page do"]),
        f(HAND,
          "Go slowly, sit up straight, and leave a finger space between words. "
          "Neat writing comes from practice, not from speed.",
          ["how can i make my writing neater",
           "how do i write more neatly",
           "how can i get better at handwriting",
           "why is my writing messy"],
          ["how do i improve my handwriting"]),
        f(HAND,
          "Leave a finger space between words so they do not bump into each "
          "other. Put one finger on the page after each word.",
          ["how much space goes between words",
           "what is a finger space",
           "why do i leave a gap between words",
           "how big should the space between words be"],
          ["how do i space out my words"]),
        f(HAND,
          "Sounding a word out means saying it slowly and listening for each "
          "sound, then writing a letter for every sound you hear.",
          ["what does sounding out a word mean",
           "how do i sound out a word",
           "what is sounding out",
           "how does sounding out help me spell"],
          ["can you explain sounding a word out"]),
        f(HAND,
          "Fun has three letters. Fun is spelled f u n.",
          ["how many letters are in the word fun",
           "how many letters does fun have",
           "how do you spell fun",
           "count the letters in fun"],
          ["how many letters make up the word fun"]),
        f(HAND,
          "Tree has four letters. Tree is spelled t r e e.",
          ["how many letters are in the word tree",
           "how many letters does tree have",
           "how do you spell tree",
           "count the letters in tree"],
          ["how many letters make up the word tree"]),
        f(HAND,
          "Happy has five letters. Happy is spelled h a p p y.",
          ["how many letters are in the word happy",
           "how many letters does happy have",
           "how do you spell happy",
           "count the letters in happy"],
          ["how many letters make up the word happy"]),
        f(HAND,
          "Elephant has eight letters. Elephant is spelled e l e p h a n t.",
          ["how many letters are in the word elephant",
           "how many letters does elephant have",
           "how do you spell elephant",
           "count the letters in elephant"],
          ["how many letters make up the word elephant"]),
        f(HAND,
          "Some words hide a letter you never say. The k in knee is silent, and "
          "so is the w in write.",
          ["what is a silent letter",
           "why do some letters not make a sound",
           "what does silent letter mean",
           "tell me about silent letters"],
          ["can you explain silent letters"]),
        f(HAND,
          "Trace the letter with your finger first, then write it slowly three "
          "times. Your hand learns the shape by repeating it.",
          ["how do i learn to write a new letter",
           "how can i practice writing letters",
           "what is the best way to learn letter shapes",
           "how do i get better at forming letters"],
          ["how should i practice a letter i find hard"]),
    ]


# --------------------------------------------------------------------------
# cursive writing
# --------------------------------------------------------------------------

def _cursive():
    return [
        f(CURSIVE,
          "Cursive is a kind of writing where the letters in a word are joined "
          "together with little curvy lines instead of standing apart.",
          ["what is cursive",
           "what does cursive mean",
           "tell me about cursive writing",
           "what is cursive writing"],
          ["can you explain what cursive is"]),
        f(CURSIVE,
          "Joined up writing is another name for cursive. The letters hold hands "
          "so your pencil does not have to lift off the page.",
          ["what is joined up writing",
           "what does joined up writing mean",
           "is joined up writing the same as cursive",
           "why is it called joined writing"],
          ["what do people mean by joined writing"]),
        f(CURSIVE,
          "In print each letter stands on its own. In cursive the letters are "
          "joined and lean a little to one side.",
          ["what is the difference between print and cursive",
           "how is cursive different from printing",
           "is printing the same as cursive",
           "what makes cursive different from normal writing"],
          ["how do print and cursive differ"]),
        f(CURSIVE,
          "People invented joined writing so the pen could keep moving. Lifting "
          "the pen for every letter was slow and smudged the ink.",
          ["why does cursive exist",
           "why did people start writing in cursive",
           "why do we join letters together",
           "who invented joined writing"],
          ["what is the reason for cursive"]),
        f(CURSIVE,
          "Once you have practiced it, cursive can be faster than printing "
          "because your pencil stays on the paper between letters.",
          ["is cursive faster than printing",
           "is cursive quicker to write",
           "does cursive save time",
           "which is faster cursive or print"],
          ["is joined writing speedier"]),
        f(CURSIVE,
          "You do not have to use cursive, but it is a handy skill. Many people "
          "use it for notes and for signing their name.",
          ["do i have to learn cursive",
           "do i need to write in cursive",
           "is cursive important",
           "should i learn cursive"],
          ["is learning cursive necessary"]),
        f(CURSIVE,
          "Most children start cursive around seven or eight years old, once "
          "printing feels easy.",
          ["when do kids learn cursive",
           "what age do you learn cursive",
           "how old are you when you learn cursive",
           "when should i start cursive"],
          ["at what age do children start cursive"]),
        f(CURSIVE,
          "Start with the easy loopy ones. Lowercase l, e, and i are mostly "
          "curves, so they are a friendly place to begin.",
          ["which cursive letters should i learn first",
           "what is the easiest cursive letter",
           "where do i start with cursive",
           "which letters are easy in cursive"],
          ["what cursive letter is a good first one"]),
        f(CURSIVE,
          "Cursive lowercase r, s, and z trip up a lot of people because their "
          "shapes do not look much like the printed versions.",
          ["which cursive letters are hard",
           "what is the hardest letter in cursive",
           "which cursive letters are tricky",
           "what cursive letters do people find difficult"],
          ["which cursive letter is the toughest"]),
        f(CURSIVE,
          "Cursive lowercase l is one tall loop, like a skinny balloon on a "
          "string, and it ends with a little tail to join the next letter.",
          ["what does a cursive l look like",
           "how do you write a cursive l",
           "tell me how to make a cursive l",
           "what shape is the cursive letter l"],
          ["how is lowercase l written in cursive"]),
        f(CURSIVE,
          "Capital letters in cursive usually join to the letter after them, but "
          "a few like capital D and capital P stand on their own.",
          ["do capital letters join in cursive",
           "are capital letters joined in cursive",
           "how do capital letters work in cursive",
           "do big letters connect in cursive"],
          ["do uppercase letters link up in cursive"]),
        f(CURSIVE,
          "Any pencil or pen works for cursive. A smooth pen helps, but you do "
          "not need anything special to practice.",
          ["do i need a special pen for cursive",
           "what pen should i use for cursive",
           "can i do cursive with a pencil",
           "what do i write cursive with"],
          ["is a special pen needed for joined writing"]),
        f(CURSIVE,
          "A signature is the way you sign your own name. Many people write "
          "theirs in cursive so it is quick and hard to copy.",
          ["what is a signature",
           "why do people sign their name in cursive",
           "what does signature mean",
           "why is a signature written in cursive"],
          ["can you explain what a signature is"]),
        f(CURSIVE,
          "Calligraphy is fancy, decorated handwriting. It is drawn slowly and "
          "carefully, more like art than like everyday notes.",
          ["what is calligraphy",
           "what does calligraphy mean",
           "is calligraphy the same as cursive",
           "tell me about calligraphy"],
          ["can you explain calligraphy"]),
        f(CURSIVE,
          "Warm up with rows of loops and waves across the page. Those two "
          "shapes hide inside almost every cursive letter.",
          ["how do i practice cursive",
           "how can i get better at cursive",
           "what is a good cursive warm up",
           "how do i learn cursive"],
          ["what is the best way to practice joined writing"]),
        f(CURSIVE,
          "Cursive leans forward a little, like it is walking into the wind. "
          "Keeping every letter leaning the same way makes it look tidy.",
          ["why does cursive lean over",
           "why is cursive slanted",
           "should cursive letters lean",
           "why does joined writing tilt"],
          ["why do cursive letters slant"]),
    ]


# --------------------------------------------------------------------------
# vocabulary
# --------------------------------------------------------------------------

def _word_types():
    return [
        f(VOCAB,
          "A noun is a naming word. It names a person, a place, an animal, or a "
          "thing. Dog, school, and pizza are all nouns.",
          ["what is a noun",
           "what does noun mean",
           "tell me what a noun is",
           "give me an example of a noun"],
          ["can you explain nouns to me"]),
        f(VOCAB,
          "A verb is a doing word. It tells you what someone is doing. Run, jump, "
          "eat, and sleep are all verbs.",
          ["what is a verb",
           "what does verb mean",
           "tell me what a verb is",
           "give me an example of a verb"],
          ["can you explain verbs to me"]),
        f(VOCAB,
          "An adjective is a describing word. It tells you more about a thing, "
          "like a red ball, a fluffy cat, or a loud drum.",
          ["what is an adjective",
           "what does adjective mean",
           "tell me what an adjective is",
           "give me an example of an adjective"],
          ["can you explain adjectives to me"]),
        f(VOCAB,
          "Nouns name things, verbs do things, and adjectives describe things. "
          "In the happy dog runs, happy describes, dog names, and runs does.",
          ["what is the difference between a noun and a verb",
           "how do i tell a noun from a verb",
           "how are nouns verbs and adjectives different",
           "how do i know if a word is a noun or a verb"],
          ["how can i tell what kind of word something is"]),
        f(VOCAB,
          "Yes, jump is a verb. It is something you do with your legs.",
          ["is jump a noun or a verb",
           "is jump a verb",
           "what kind of word is jump",
           "what type of word is the word jump"],
          ["is the word jump a doing word"]),
        f(VOCAB,
          "Cat is a noun, because it names an animal.",
          ["is cat a noun or a verb",
           "is cat a noun",
           "what kind of word is cat",
           "what type of word is the word cat"],
          ["is the word cat a naming word"]),
        f(VOCAB,
          "Shiny is an adjective, because it describes how something looks.",
          ["is shiny a noun or an adjective",
           "is shiny an adjective",
           "what kind of word is shiny",
           "what type of word is the word shiny"],
          ["is the word shiny a describing word"]),
        f(VOCAB,
          "A sentence is a group of words that tells a whole idea. It starts with "
          "a capital letter and ends with a period.",
          ["what is a sentence",
           "what does sentence mean",
           "tell me what a sentence is",
           "what makes a sentence"],
          ["can you explain what a sentence is"]),
        f(VOCAB,
          "The dog ran fast is a sentence, because it tells you who did something "
          "and what they did.",
          ["can you give me an example of a sentence",
           "say a sentence for me",
           "show me what a sentence looks like",
           "tell me an example sentence"],
          ["what is an example of a good sentence"]),
        f(VOCAB,
          "A question is a sentence that asks something. It ends with a question "
          "mark instead of a period, like where is my hat?",
          ["what is a question",
           "what does question mean",
           "how is a question different from a sentence",
           "what makes a sentence a question"],
          ["can you explain what a question is"]),
        f(VOCAB,
          "A period is the little dot at the end of a sentence. It tells you to "
          "stop and take a breath.",
          ["what is a period at the end of a sentence",
           "what is the dot at the end of a sentence",
           "what does a period do",
           "why do sentences end with a dot"],
          ["what is that dot at the end of a sentence for"]),
        f(VOCAB,
          "An exclamation point is the tall mark that shows excitement, like in "
          "watch out! It means say it with feeling.",
          ["what is an exclamation point",
           "what does an exclamation mark do",
           "why do some sentences end with an exclamation point",
           "what is the tall mark at the end of a sentence"],
          ["can you explain an exclamation point"]),
        f(VOCAB,
          "A compound word is two small words stuck together to make a new one. "
          "Sunflower is sun plus flower.",
          ["what is a compound word",
           "what does compound word mean",
           "give me an example of a compound word",
           "tell me what a compound word is"],
          ["can you explain compound words"]),
        f(VOCAB,
          "Rainbow is a compound word. It is rain plus bow. Butterfly is butter "
          "plus fly.",
          ["what two words make rainbow",
           "is rainbow a compound word",
           "what small words are inside rainbow",
           "break the word rainbow into two words"],
          ["what is rainbow made of"]),
        f(VOCAB,
          "Putting un in front of a word flips its meaning. Happy becomes unhappy "
          "and tie becomes untie.",
          ["what does un mean at the start of a word",
           "what does the word part un do",
           "why do some words start with un",
           "what happens when you put un in front of a word"],
          ["what does adding un to a word do"]),
    ]


def _rhyme_syllables():
    return [
        f(VOCAB,
          "Words rhyme when they end with the same sound, like cat and hat, or "
          "star and car.",
          ["what does rhyming mean",
           "what is a rhyme",
           "what does it mean when words rhyme",
           "tell me what rhyming is"],
          ["can you explain rhyming words"]),
        f(VOCAB,
          "Hat, bat, mat, and sat all rhyme with cat. They all end with the at "
          "sound.",
          ["what rhymes with cat",
           "tell me a word that rhymes with cat",
           "give me rhymes for cat",
           "which words rhyme with cat"],
          ["what word sounds like cat at the end"]),
        f(VOCAB,
          "Log, frog, jog, and fog all rhyme with dog.",
          ["what rhymes with dog",
           "tell me a word that rhymes with dog",
           "give me rhymes for dog",
           "which words rhyme with dog"],
          ["what word sounds like dog at the end"]),
        f(VOCAB,
          "Fun, run, bun, and one all rhyme with sun.",
          ["what rhymes with sun",
           "tell me a word that rhymes with sun",
           "give me rhymes for sun",
           "which words rhyme with sun"],
          ["what word sounds like sun at the end"]),
        f(VOCAB,
          "Bee, see, key, and free all rhyme with tree.",
          ["what rhymes with tree",
           "tell me a word that rhymes with tree",
           "give me rhymes for tree",
           "which words rhyme with tree"],
          ["what word sounds like tree at the end"]),
        f(VOCAB,
          "Car, jar, far, and guitar all rhyme with star.",
          ["what rhymes with star",
           "tell me a word that rhymes with star",
           "give me rhymes for star",
           "which words rhyme with star"],
          ["what word sounds like star at the end"]),
        f(VOCAB,
          "A syllable is a beat in a word. Clap once for each beat and you will "
          "count them.",
          ["what is a syllable",
           "what does syllable mean",
           "tell me what a syllable is",
           "how do i count syllables"],
          ["can you explain syllables"]),
        f(VOCAB,
          "Cat has one syllable. You only clap once when you say it.",
          ["how many syllables are in cat",
           "how many syllables does cat have",
           "how many beats are in the word cat",
           "how many claps for the word cat"],
          ["what is the syllable count for cat"]),
        f(VOCAB,
          "Banana has three syllables. Ba na na. Clap once for each part.",
          ["how many syllables are in banana",
           "how many syllables does banana have",
           "how many beats are in the word banana",
           "how many claps for the word banana"],
          ["what is the syllable count for banana"]),
        f(VOCAB,
          "Elephant has three syllables. El e phant.",
          ["how many syllables are in elephant",
           "how many syllables does elephant have",
           "how many beats are in the word elephant",
           "how many claps for the word elephant"],
          ["what is the syllable count for elephant"]),
        f(VOCAB,
          "Butterfly has three syllables. But ter fly.",
          ["how many syllables are in butterfly",
           "how many syllables does butterfly have",
           "how many beats are in the word butterfly",
           "how many claps for the word butterfly"],
          ["what is the syllable count for butterfly"]),
        f(VOCAB,
          "Computer has three syllables. Com pu ter.",
          ["how many syllables are in computer",
           "how many syllables does computer have",
           "how many beats are in the word computer",
           "how many claps for the word computer"],
          ["what is the syllable count for computer"]),
    ]


def _plurals():
    return [
        f(VOCAB,
          "Plural means more than one. Most words just add an s, so one dog "
          "becomes two dogs.",
          ["what does plural mean",
           "what is a plural",
           "how do i make a word mean more than one",
           "tell me what plural means"],
          ["can you explain plurals"]),
        f(VOCAB,
          "More than one box is boxes. Words ending in x, s, ch, or sh add e s "
          "instead of just s.",
          ["what is more than one box",
           "what is the plural of box",
           "how do you say box when there are lots",
           "how do i make box plural"],
          ["what do you call many boxes"]),
        f(VOCAB,
          "More than one baby is babies. When a word ends in y, the y turns into "
          "i e s.",
          ["what is more than one baby",
           "what is the plural of baby",
           "how do you say baby when there are lots",
           "how do i make baby plural"],
          ["what do you call many babies"]),
        f(VOCAB,
          "More than one child is children. That one does not follow the rules.",
          ["what is more than one child",
           "what is the plural of child",
           "how do you say child when there are lots",
           "how do i make child plural"],
          ["what do you call many children"]),
        f(VOCAB,
          "More than one mouse is mice.",
          ["what is more than one mouse",
           "what is the plural of mouse",
           "how do you say mouse when there are lots",
           "how do i make mouse plural"],
          ["what do you call many mice"]),
        f(VOCAB,
          "More than one foot is feet.",
          ["what is more than one foot",
           "what is the plural of foot",
           "how do you say foot when there are lots",
           "how do i make foot plural"],
          ["what do you call two feet"]),
        f(VOCAB,
          "More than one tooth is teeth.",
          ["what is more than one tooth",
           "what is the plural of tooth",
           "how do you say tooth when there are lots",
           "how do i make tooth plural"],
          ["what do you call all your teeth"]),
        f(VOCAB,
          "More than one man is men, and more than one woman is women.",
          ["what is more than one man",
           "what is the plural of man",
           "how do you say man when there are lots",
           "how do i make man plural"],
          ["what do you call many men"]),
        f(VOCAB,
          "More than one goose is geese.",
          ["what is more than one goose",
           "what is the plural of goose",
           "how do you say goose when there are lots",
           "how do i make goose plural"],
          ["what do you call many geese"]),
        f(VOCAB,
          "More than one leaf is leaves. The f changes into a v.",
          ["what is more than one leaf",
           "what is the plural of leaf",
           "how do you say leaf when there are lots",
           "how do i make leaf plural"],
          ["what do you call many leaves"]),
        f(VOCAB,
          "Sheep stays sheep, and fish stays fish. One sheep or a hundred sheep, "
          "the word does not change.",
          ["what is more than one sheep",
           "what is the plural of sheep",
           "does sheep change when there is more than one",
           "what is the plural of fish"],
          ["what do you call lots of sheep"]),
    ]


def _synonyms_opposites():
    return [
        f(VOCAB,
          "A synonym is a word that means almost the same as another word. Big "
          "and large are synonyms.",
          ["what is a synonym",
           "what does synonym mean",
           "tell me what a synonym is",
           "what do you call words that mean the same"],
          ["can you explain synonyms"]),
        f(VOCAB,
          "An opposite is a word that means the other end of something. Hot is "
          "the opposite of cold. Grown ups call it an antonym.",
          ["what is an opposite",
           "what does opposite mean",
           "what is an antonym",
           "tell me what an opposite word is"],
          ["can you explain opposite words"]),
        f(VOCAB,
          "Large, huge, and giant all mean about the same as big.",
          ["what is another word for big",
           "what word means the same as big",
           "give me a synonym for big",
           "what else can i say instead of big"],
          ["what is a different word for big"]),
        f(VOCAB,
          "Glad, cheerful, and joyful all mean about the same as happy.",
          ["what is another word for happy",
           "what word means the same as happy",
           "give me a synonym for happy",
           "what else can i say instead of happy"],
          ["what is a different word for happy"]),
        f(VOCAB,
          "Little, tiny, and small all mean the same kind of thing.",
          ["what is another word for small",
           "what word means the same as small",
           "give me a synonym for small",
           "what else can i say instead of small"],
          ["what is a different word for small"]),
        f(VOCAB,
          "Quick, speedy, and swift all mean about the same as fast.",
          ["what is another word for fast",
           "what word means the same as fast",
           "give me a synonym for fast",
           "what else can i say instead of fast"],
          ["what is a different word for fast"]),
        f(VOCAB,
          "Unhappy, gloomy, and blue all mean about the same as sad.",
          ["what is another word for sad",
           "what word means the same as sad",
           "give me a synonym for sad",
           "what else can i say instead of sad"],
          ["what is a different word for sad"]),
        f(VOCAB,
          "Clever, bright, and wise all mean about the same as smart.",
          ["what is another word for smart",
           "what word means the same as smart",
           "give me a synonym for smart",
           "what else can i say instead of smart"],
          ["what is a different word for smart"]),
        f(VOCAB,
          "Afraid, frightened, and nervous all mean about the same as scared.",
          ["what is another word for scared",
           "what word means the same as scared",
           "give me a synonym for scared",
           "what else can i say instead of scared"],
          ["what is a different word for scared"]),
        f(VOCAB,
          "The opposite of hot is cold.",
          ["what is the opposite of hot",
           "what is the other end of hot",
           "hot is the opposite of what",
           "give me the opposite of hot"],
          ["what word means the opposite of hot"]),
        f(VOCAB,
          "The opposite of big is small.",
          ["what is the opposite of big",
           "what is the other end of big",
           "big is the opposite of what",
           "give me the opposite of big"],
          ["what word means the opposite of big"]),
        f(VOCAB,
          "The opposite of up is down.",
          ["what is the opposite of up",
           "what is the other end of up",
           "up is the opposite of what",
           "give me the opposite of up"],
          ["what word means the opposite of up"]),
        f(VOCAB,
          "The opposite of day is night.",
          ["what is the opposite of day",
           "what is the other end of day",
           "day is the opposite of what",
           "give me the opposite of day"],
          ["what word means the opposite of day"]),
        f(VOCAB,
          "The opposite of happy is sad.",
          ["what is the opposite of happy",
           "what is the other end of happy",
           "happy is the opposite of what",
           "give me the opposite of happy"],
          ["what word means the opposite of happy"]),
        f(VOCAB,
          "The opposite of wet is dry.",
          ["what is the opposite of wet",
           "what is the other end of wet",
           "wet is the opposite of what",
           "give me the opposite of wet"],
          ["what word means the opposite of wet"]),
        f(VOCAB,
          "The opposite of fast is slow.",
          ["what is the opposite of fast",
           "what is the other end of fast",
           "fast is the opposite of what",
           "give me the opposite of fast"],
          ["what word means the opposite of fast"]),
        f(VOCAB,
          "The opposite of old is new when you mean things, and young when you "
          "mean people.",
          ["what is the opposite of old",
           "what is the other end of old",
           "old is the opposite of what",
           "give me the opposite of old"],
          ["what word means the opposite of old"]),
        f(VOCAB,
          "The opposite of hard is soft when you mean touching it, and easy when "
          "you mean doing it.",
          ["what is the opposite of hard",
           "what is the other end of hard",
           "hard is the opposite of what",
           "give me the opposite of hard"],
          ["what word means the opposite of hard"]),
        f(VOCAB,
          "The opposite of light is dark.",
          ["what is the opposite of light",
           "what is the other end of light",
           "light is the opposite of what",
           "give me the opposite of light"],
          ["what word means the opposite of light"]),
        f(VOCAB,
          "The opposite of over is under.",
          ["what is the opposite of over",
           "what is the other end of over",
           "over is the opposite of what",
           "give me the opposite of over"],
          ["what word means the opposite of over"]),
        f(VOCAB,
          "The opposite of full is empty.",
          ["what is the opposite of full",
           "what is the other end of full",
           "full is the opposite of what",
           "give me the opposite of full"],
          ["what word means the opposite of full"]),
        f(VOCAB,
          "The opposite of loud is quiet.",
          ["what is the opposite of loud",
           "what is the other end of loud",
           "loud is the opposite of what",
           "give me the opposite of loud"],
          ["what word means the opposite of loud"]),
        f(VOCAB,
          "The opposite of open is closed.",
          ["what is the opposite of open",
           "what is the other end of open",
           "open is the opposite of what",
           "give me the opposite of open"],
          ["what word means the opposite of open"]),
        f(VOCAB,
          "The opposite of push is pull.",
          ["what is the opposite of push",
           "what is the other end of push",
           "push is the opposite of what",
           "give me the opposite of push"],
          ["what word means the opposite of push"]),
        f(VOCAB,
          "The opposite of before is after.",
          ["what is the opposite of before",
           "what is the other end of before",
           "before is the opposite of what",
           "give me the opposite of before"],
          ["what word means the opposite of before"]),
        f(VOCAB,
          "The opposite of left is right.",
          ["what is the opposite of left",
           "what is the other end of left",
           "left is the opposite of what",
           "give me the opposite of left"],
          ["what word means the opposite of left"]),
        f(VOCAB,
          "The opposite of in is out.",
          ["what is the opposite of in",
           "what is the other end of in",
           "in is the opposite of what",
           "give me the opposite of in"],
          ["what word means the opposite of in"]),
    ]


def _meanings():
    """Words a five to eight year old actually bumps into."""
    table = [
        ("huge", "Huge means very, very big. An elephant is huge next to a mouse."),
        ("tiny", "Tiny means very, very small. An ant is tiny."),
        ("enormous", "Enormous means really huge. A whale is enormous."),
        ("curious", "Curious means you want to find out about things. A curious "
                    "kid asks lots of questions."),
        ("brave", "Brave means doing something even though it feels a bit "
                  "scary, like trying a new slide."),
        ("kind", "Kind means being nice to people and caring how they feel, "
                 "like sharing your toys."),
        ("polite", "Polite means using good manners, like saying please and "
                   "thank you and waiting your turn."),
        ("gentle", "Gentle means soft and careful, the way you pet a kitten."),
        ("clumsy", "Clumsy means you bump into things and drop stuff by "
                   "accident. Everybody is clumsy sometimes."),
        ("giggle", "To giggle is to laugh in a small bubbly way, the kind you "
                   "try to hide behind your hand."),
        ("whisper", "To whisper is to talk very quietly, so only the person "
                    "next to you can hear."),
        ("shout", "To shout is to say something very loudly, so people far "
                  "away can hear you."),
        ("stroll", "To stroll is to walk slowly, just taking your time."),
        ("sprint", "To sprint is to run as fast as you possibly can, for a "
                   "short way."),
        ("delicious", "Delicious means it tastes really good. A warm cookie is "
                      "delicious."),
        ("sour", "Sour is the sharp taste that makes your face scrunch up, "
                 "like a lemon."),
        ("sticky", "Sticky means it clings to your fingers, like honey or glue."),
        ("fluffy", "Fluffy means soft and puffy, like a cloud or a bunny."),
        ("shiny", "Shiny means it catches the light and sparkles, like a new "
                  "coin."),
        ("soggy", "Soggy means wet and floppy, like cereal left in milk too "
                  "long."),
        ("chilly", "Chilly means a little bit cold. You want a sweater, but "
                   "not a big coat."),
        ("ancient", "Ancient means very, very old. Dinosaurs lived in ancient "
                    "times."),
        ("tidy", "Tidy means everything is neat and put away in its place."),
        ("grumpy", "Grumpy means a bit cross and unhappy, the way you feel "
                   "when you wake up too early."),
        ("cozy", "Cozy means warm and comfy, like being under a blanket."),
        ("sturdy", "Sturdy means strong and solid, so it will not wobble or "
                   "break."),
        ("eager", "Eager means you really want to do something and can hardly "
                  "wait."),
        ("nervous", "Nervous means a little worried, with a wobbly feeling in "
                    "your tummy."),
        ("gigantic", "Gigantic means gigantically big, even bigger than huge."),
        ("silly", "Silly means funny in a goofy way, like wearing socks on "
                  "your hands."),
        ("brilliant", "Brilliant means really bright, or really clever. A "
                      "brilliant idea is a very good one."),
        ("rescue", "To rescue is to save someone from trouble, the way "
                   "firefighters rescue a cat from a tree."),
        ("wander", "To wander is to walk about without going anywhere in "
                   "particular."),
        ("gather", "To gather is to collect things together into one place, "
                   "like gathering leaves into a pile."),
        ("shiver", "To shiver is to shake a little because you are cold or "
                   "excited."),
    ]
    out = []
    for word, answer in table:
        out.append(f(VOCAB, answer,
                     [f"what does {word} mean",
                      f"what is the meaning of {word}",
                      f"tell me what {word} means",
                      f"can you explain the word {word}"],
                     [f"what does the word {word} mean"]))
    return out


# --------------------------------------------------------------------------
# jokes & fun
# --------------------------------------------------------------------------

JOKE_TABLE = [
    ("cows", "Why did the cow go to outer space? To see the moooon!"),
    ("bananas", "Why did the banana go to the doctor? Because it was not "
                "peeling well!"),
    ("skeletons", "Why did the skeleton stay home from the party? Because he "
                  "had no body to go with!"),
    ("chickens", "Why did the chicken cross the playground? To get to the "
                 "other slide!"),
    ("eggs", "Why do eggs never tell jokes? Because they would crack each "
             "other up!"),
    ("scarecrows", "Why did the scarecrow win a prize? Because he was "
                   "outstanding in his field!"),
    ("bicycles", "Why could the bicycle not stand up by itself? Because it "
                 "was two tired!"),
    ("math", "Why was the math book so sad? Because it had too many problems!"),
    ("teddy bears", "Why did the teddy bear say no to dessert? Because he was "
                    "already stuffed!"),
    ("the moon", "Why did the moon skip dinner? Because it was already full!"),
    ("computers", "Why did the computer go to the doctor? Because it had a "
                  "bug!"),
    ("the ocean", "What did the ocean say to the shore? Nothing, it just "
                  "waved!"),
    ("fish", "Where do fish keep their money? In the riverbank!"),
    ("bees", "What do you call a bee that cannot make up its mind? A maybe!"),
    ("cats", "Why are cats such good singers? Because they are very mewsical!"),
    ("dogs", "What kind of dog always knows the time? A watch dog!"),
    ("elephants", "Why do elephants never use computers? Because they are "
                  "scared of the mouse!"),
    ("lions", "Why did the lion lose at cards? Because he was playing with a "
              "cheetah!"),
    ("cheetahs", "Why are cheetahs bad at hide and seek? Because they are "
                 "always spotted!"),
    ("frogs", "What happens when a frog's car breaks down? It gets toad away!"),
    ("ducks", "What time do ducks wake up? At the quack of dawn!"),
    ("pigs", "Where do pigs park their cars? In the porking lot!"),
    ("horses", "Why did the horse eat with its mouth open? Because it had bad "
               "stable manners!"),
    ("sheep", "What do sheep say to each other in December? Merry Christmas "
              "to ewe!"),
    ("monkeys", "What is a monkey's favorite cookie? A chocolate chimp cookie!"),
    ("penguins", "What do penguins wear on their heads? Ice caps!"),
    ("snowmen", "What do snowmen eat for breakfast? Snowflakes!"),
    ("bears", "What do you call a bear with no teeth? A gummy bear!"),
    ("rabbits", "What kind of music do rabbits like best? Hip hop!"),
    ("owls", "Why did the owl invite his friends over? Because he did not "
             "want to be owl by himself!"),
    ("spiders", "What did the spider do on the computer? It made a website!"),
    ("bats", "Why do bats like caves so much? Because they love to hang out!"),
    ("snakes", "What do you call a snake that builds houses? A boa "
               "constructor!"),
    ("turtles", "Why did the turtle cross the road? To get to the shell "
                "station!"),
    ("whales", "Why are whales such good singers? Because they know all the "
               "deep songs!"),
    ("sharks", "What is a shark's favorite sandwich? Peanut butter and "
               "jellyfish!"),
    ("octopuses", "Why did the octopus blush? Because it saw the bottom of "
                  "the ocean!"),
    ("crabs", "Why are crabs so bad at sharing? Because they are shellfish!"),
    ("bread", "Why did the bread go to the party? Because it was on a roll!"),
    ("cheese", "What do you call cheese that is not yours? Nacho cheese!"),
    ("pizza", "Why did the pizza win an award? Because it was extra cheesy!"),
    ("cookies", "Why did the cookie go to the doctor? Because it was feeling "
                "crummy!"),
    ("potatoes", "What do you call a potato that never gets off the sofa? A "
                 "couch potato!"),
    ("carrots", "What do you call a carrot that talks back? A fresh "
                "vegetable!"),
    ("tomatoes", "Why did the tomato turn red? Because it saw the salad "
                 "dressing!"),
    ("corn", "What did the baby corn say to the mama corn? Where is pop corn!"),
    ("oranges", "Why did the orange stop rolling down the hill? Because it "
                "ran out of juice!"),
    ("apples", "What do you call an apple that plays the trumpet? A tooty "
               "fruity!"),
    ("grapes", "Why are grapes never lonely? Because they come in bunches!"),
    ("ice cream", "What is an ice cream's favorite day of the week? Sundae!"),
    ("clocks", "Why did the clock get sent to the principal? Because it "
               "tocked too much!"),
    ("pencils", "Why was the pencil feeling sad? Because it thought it was "
                "pointless!"),
    ("books", "Why did the book go to the hospital? Because it hurt its "
              "spine!"),
    ("school", "Why did the kid eat his homework? Because the teacher said it "
               "was a piece of cake!"),
    ("teachers", "Why did the teacher wear sunglasses to class? Because her "
                 "students were so bright!"),
    ("crayons", "Why was the crayon so tired? Because it had been worn all "
                "the way down!"),
    ("trains", "What do you call a train that has a cold? An achoo choo "
               "train!"),
    ("cars", "Why did the car take a nap? Because it was feeling tired!"),
    ("airplanes", "Why did the airplane get sent to bed early? Because it had "
                  "a bad altitude!"),
    ("boats", "What is a boat's favorite kind of story? A ferry tale!"),
    ("the sun", "Why did the sun go to school? Because it wanted to get "
                "brighter!"),
    ("stars", "How do you know the stars are friendly? Because they always "
              "twinkle at you!"),
    ("clouds", "Why was the cloud in such a good mood? Because it was feeling "
               "light!"),
    ("rain", "What did one raindrop say to the other raindrop? Two is "
             "company, three is a cloud!"),
    ("snow", "What do you call a snowman in the middle of summer? A puddle!"),
    ("trees", "Why was the tree so cheerful? Because it was really poplar!"),
    ("flowers", "What did the big flower say to the little flower? Hi there, "
                "bud!"),
    ("robots", "Why was the robot so tired? Because it had a hard drive!"),
    ("dinosaurs", "What do you call a dinosaur that sleeps all day? A dino "
                  "snore!"),
    ("ants", "Why do ants never get sick? Because they have tiny anty bodies!"),
    ("butterflies", "Why are butterflies such good dancers? Because they know "
                    "all the flutter steps!"),
    ("kangaroos", "What do you call a kangaroo that lies around all day? A "
                  "pouch potato!"),
    ("giraffes", "Why do giraffes take so long to say sorry? Because it takes "
                 "ages to swallow their pride!"),
    ("zebras", "Why did the zebra get a job? Because it wanted to earn its "
               "stripes!"),
    ("hippos", "What do you call a hippo that plays music? A hip pop star!"),
    ("birds", "Which bird is always out of breath? A puffin!"),
    ("mice", "What is a mouse's favorite game to play? Hide and squeak!"),
    ("cake", "Why was the birthday cake so hard to cut? Because it was a "
             "marble cake!"),
    ("soccer", "Why did the soccer ball quit the team? Because it was tired "
               "of being kicked around!"),
    ("shoes", "What did one shoe say to the other shoe? You are my sole mate!"),
    ("socks", "Why did the sock go to the doctor? Because it had a hole lot "
              "of trouble!"),
]


def _bare_jokes():
    return [
        f(JOKES,
          "What do you call a sleeping pizza? A pizzzza!",
          ["tell me a joke",
           "say a joke",
           "can you tell me a joke",
           "i want a joke"],
          ["tell me a joke please"]),
        f(JOKES,
          "Why did the student bring a ladder to school? Because she wanted to "
          "go to high school!",
          ["tell me another joke",
           "another joke please",
           "one more joke",
           "give me another joke"],
          ["can i have another joke"]),
        f(JOKES,
          "What is brown and sticky? A stick!",
          ["make me laugh",
           "say something funny",
           "can you make me laugh",
           "be funny"],
          ["i want to laugh"]),
        f(JOKES,
          "What do you call a pretend noodle? An impasta!",
          ["tell me a silly joke",
           "say a silly joke",
           "i want a silly joke",
           "give me a goofy joke"],
          ["do you know a silly joke"]),
        f(JOKES,
          "I know loads of jokes! Here is one. What has four wheels and flies? "
          "A trash truck!",
          ["do you know any jokes",
           "are you funny",
           "do you know a good joke",
           "do you like telling jokes"],
          ["have you got any good jokes"]),
        f(JOKES,
          "My favorite joke is this one. Why do seagulls fly over the sea? "
          "Because if they flew over the bay they would be bagels!",
          ["what is your favorite joke",
           "tell me the best joke",
           "what is the funniest joke you know",
           "say your best joke"],
          ["which joke do you like most"]),
        f(JOKES,
          "Knock knock. Who is there? Lettuce. Lettuce who? Lettuce in, it is "
          "chilly out here!",
          ["tell me a knock knock joke",
           "say a knock knock joke",
           "do you know a knock knock joke",
           "i want a knock knock joke"],
          ["can you do a knock knock joke"]),
        f(JOKES,
          "Knock knock. Who is there? Boo. Boo who? Oh do not cry, it is only "
          "a joke!",
          ["tell me another knock knock joke",
           "one more knock knock joke",
           "another knock knock please",
           "do you know a second knock knock joke"],
          ["can i have another knock knock joke"]),
        f(JOKES,
          "Knock knock. Who is there? Cow says. Cow says who? No silly, a cow "
          "says moo!",
          ["tell me a funny knock knock joke about animals",
           "do you know an animal knock knock joke",
           "say a knock knock joke with an animal",
           "i want an animal knock knock joke"],
          ["have you got a knock knock joke about animals"]),
    ]


TWISTERS = [
    ("she sells seashells",
     "She sells seashells by the seashore. Say it three times fast!"),
    ("peter piper",
     "Peter Piper picked a peck of pickled peppers. How many peppers did "
     "Peter Piper pick?"),
    ("woodchuck",
     "How much wood would a woodchuck chuck if a woodchuck could chuck wood?"),
    ("rubber baby",
     "Rubber baby buggy bumpers. Try saying that five times in a row!"),
    ("fuzzy wuzzy",
     "Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy was not "
     "very fuzzy, was he?"),
    ("toy boat",
     "Toy boat. Toy boat. Toy boat. It sounds easy until you speed up!"),
    ("unique new york",
     "Unique New York. You know you need unique New York. Your tongue will "
     "tie itself in a knot!"),
    ("red truck yellow truck",
     "Red truck, yellow truck, red truck, yellow truck. Say it faster and "
     "faster!"),
]


def _twisters():
    out = [
        f(JOKES,
          "A tongue twister is a sentence full of similar sounds that is really "
          "tricky to say fast, like she sells seashells by the seashore.",
          ["what is a tongue twister",
           "what does tongue twister mean",
           "tell me what a tongue twister is",
           "why is it called a tongue twister"],
          ["can you explain tongue twisters"]),
        f(JOKES,
          "Here is one. She sells seashells by the seashore. Now try it three "
          "times without slowing down!",
          ["tell me a tongue twister",
           "say a tongue twister",
           "i want a tongue twister",
           "can you do a tongue twister"],
          ["give me a tongue twister"]),
    ]
    for key, answer in TWISTERS:
        out.append(f(JOKES, answer,
                     [f"tell me the {key} tongue twister",
                      f"say the {key} tongue twister",
                      f"do you know the {key} tongue twister",
                      f"how does the {key} tongue twister go"],
                     [f"can you say {key}"]))
    return out


RIDDLES = [
    ("hands but cannot clap",
     ["what has hands but cannot clap",
      "what has two hands and no fingers",
      "riddle about hands that cannot clap",
      "what thing has hands but never claps"],
     ["what has hands but never claps"],
     "A clock! It has hands, but it cannot clap them."),
    ("keys but cannot open locks",
     ["what has keys but cannot open locks",
      "what has lots of keys and no doors",
      "riddle about keys that open nothing",
      "what thing has keys but no locks"],
     ["what has keys but opens no doors"],
     "A piano! It has lots of keys but not one lock."),
    ("wetter as it dries",
     ["what gets wetter the more it dries",
      "what gets wet while drying things",
      "riddle about something that gets wetter as it dries",
      "what thing gets wetter when it dries you"],
     ["what becomes wetter the more it dries"],
     "A towel! The more it dries you off, the wetter it gets."),
    ("neck but no head",
     ["what has a neck but no head",
      "what has a neck and never wears a hat",
      "riddle about a neck with no head",
      "what thing has a neck but no head at all"],
     ["what has a neck without a head"],
     "A bottle! It has a neck but no head."),
    ("up but never down",
     ["what goes up but never comes down",
      "what only ever goes up",
      "riddle about something that never comes down",
      "what thing goes up and stays up"],
     ["what always goes up and never comes back down"],
     "Your age! It goes up every birthday and never comes back down."),
    ("one eye but cannot see",
     ["what has one eye but cannot see",
      "what has an eye and no face",
      "riddle about one eye that cannot see",
      "what thing has a single eye but is blind"],
     ["what has an eye but cannot see anything"],
     "A needle! It has an eye, but it cannot see a thing."),
    ("teeth but cannot bite",
     ["what has many teeth but cannot bite",
      "what has teeth and never eats",
      "riddle about teeth that cannot bite",
      "what thing is full of teeth but never bites"],
     ["what has lots of teeth but no mouth"],
     "A comb! It is full of teeth but it cannot bite."),
    ("legs but cannot walk",
     ["what has four legs but cannot walk",
      "what has legs and stays still",
      "riddle about legs that cannot walk",
      "what thing has legs but never moves"],
     ["what has four legs and never takes a step"],
     "A table! It has four legs but it never walks anywhere."),
    ("full of holes holds water",
     ["what is full of holes but still holds water",
      "what has holes everywhere and holds water",
      "riddle about holes that hold water",
      "what thing is holey but still holds water"],
     ["what is covered in holes yet holds water"],
     "A sponge! It is full of holes and it still holds water."),
    ("catch but not throw",
     ["what can you catch but not throw",
      "what do you catch and never throw back",
      "riddle about catching something you cannot throw",
      "what thing can be caught but never thrown"],
     ["what is something you catch but cannot throw"],
     "A cold! You can catch one, but you cannot throw it."),
    ("runs but never walks",
     ["what runs but never walks",
      "what runs all day and has no legs",
      "riddle about running without legs",
      "what thing runs but has no feet"],
     ["what runs and yet has no legs"],
     "A river! It runs all day long and never takes a step."),
    ("thumb and four fingers not alive",
     ["what has a thumb and four fingers but is not alive",
      "what has fingers and is not a hand",
      "riddle about fingers that are not alive",
      "what thing has five fingers but no bones"],
     ["what has fingers and a thumb but is not living"],
     "A glove! It has a thumb and four fingers and it is not alive."),
    ("end of a rainbow",
     ["what is at the end of a rainbow",
      "what comes at the end of the word rainbow",
      "riddle about the end of a rainbow",
      "what is the last part of a rainbow"],
     ["what do you find at the end of rainbow"],
     "The letter w! It is the last letter in the word rainbow."),
    ("goes around the world stays in a corner",
     ["what goes all around the world but stays in a corner",
      "what travels the world without moving",
      "riddle about staying in a corner and going around the world",
      "what thing goes everywhere but never leaves its corner"],
     ["what sits in a corner and travels the whole world"],
     "A stamp! It sits in the corner of a letter and travels everywhere."),
]


def _riddles():
    out = [
        f(JOKES,
          "A riddle is a puzzle question with a clever answer. Here is one. "
          "What has hands but cannot clap? A clock!",
          ["what is a riddle",
           "what does riddle mean",
           "tell me what a riddle is",
           "explain riddles to me"],
          ["can you tell me what riddles are"]),
        f(JOKES,
          "Here is a riddle for you. What has a face and two hands but no arms "
          "or legs? A clock!",
          ["tell me a riddle",
           "say a riddle",
           "i want a riddle",
           "can you do a riddle"],
          ["give me a riddle"]),
    ]
    for _key, train, evalq, answer in RIDDLES:
        out.append(f(JOKES, answer, train, evalq))
    return out


def _fun_misc():
    return [
        f(JOKES,
          "A pun is a joke that plays with a word having two meanings. A boat's "
          "favorite story is a ferry tale, because ferry sounds like fairy.",
          ["what is a pun",
           "what does pun mean",
           "tell me what a pun is",
           "why are puns funny"],
          ["can you explain puns"]),
        f(JOKES,
          "Laughing is good for you. It relaxes your body and makes you feel "
          "happier, which is why a good joke feels so nice.",
          ["why is laughing good for you",
           "why do we laugh",
           "is laughing good for me",
           "what does laughing do to your body"],
          ["why does laughing feel so good"]),
        f(JOKES,
          "Being silly is wonderful. Wear socks on your hands, talk like a "
          "robot, or make up a word. Silly is how good ideas warm up.",
          ["can you be silly",
           "say something silly",
           "tell me something silly",
           "be silly with me"],
          ["will you be silly for me"]),
        f(JOKES,
          "The funniest animals are probably penguins, because they waddle "
          "about in tiny tuxedos and then flop onto their tummies to slide.",
          ["what is the funniest animal",
           "which animal is the silliest",
           "what animal makes you laugh",
           "what is the most hilarious animal"],
          ["which animal do you find funniest"]),
        f(JOKES,
          "A good joke has a surprise at the end. Set up the story, then flip "
          "it with a punch line nobody saw coming.",
          ["how do i tell a good joke",
           "what makes a joke funny",
           "how can i be funny",
           "how do i make someone laugh"],
          ["what is the secret to a funny joke"]),
        f(JOKES,
          "The punch line is the last bit of a joke, the surprise that makes "
          "everybody laugh. Save it for the very end.",
          ["what is a punch line",
           "what does punch line mean",
           "what is the end of a joke called",
           "tell me what a punch line is"],
          ["can you explain the punch line"]),
    ]


# --------------------------------------------------------------------------
# about me
# --------------------------------------------------------------------------

def _about_me():
    return [
        f(ME,
          "I am Braino! I am a little learning gadget. You talk to me and I "
          "answer your questions about words, numbers, animals, and the world.",
          ["who are you",
           "what are you",
           "tell me about yourself",
           "what is braino"],
          ["can you tell me who you are"]),
        f(ME,
          "My name is Braino.",
          ["what is your name",
           "what are you called",
           "do you have a name",
           "tell me your name"],
          ["what should i call you"]),
        f(ME,
          "Braino has six letters. Braino is spelled b r a i n o.",
          ["how do you spell your name",
           "how do you spell braino",
           "how many letters are in braino",
           "can you spell your name for me"],
          ["spell braino for me"]),
        f(ME,
          "I can answer questions, help you with spelling and numbers, explain "
          "what words mean, tell you jokes, and share facts about the world.",
          ["what can you do",
           "what are you good at",
           "what things can you help me with",
           "tell me what you can do"],
          ["what kinds of things do you do"]),
        f(ME,
          "Just talk to me! Ask a question out loud and I will listen and "
          "answer. You can ask me anything you are curious about.",
          ["how do i use you",
           "how do i talk to you",
           "how do i ask you something",
           "what do i do with you"],
          ["how am i supposed to use you"]),
        f(ME,
          "Yes, I can hear you just fine. I have a little microphone that "
          "listens when you speak.",
          ["can you hear me",
           "are you listening",
           "do you hear what i say",
           "can you hear my voice"],
          ["are you able to hear me"]),
        f(ME,
          "No, I cannot see anything. I only listen and talk, so you will have "
          "to describe things to me with words.",
          ["can you see me",
           "do you have eyes",
           "can you see things",
           "are you able to see"],
          ["can you look at me"]),
        f(ME,
          "I am a kind of little computer, so you could call me a robot. I do "
          "not have arms or legs though, just a voice.",
          ["are you a robot",
           "are you a computer",
           "are you a machine",
           "what kind of thing are you"],
          ["would you call yourself a robot"]),
        f(ME,
          "I am not alive the way you are. I do not eat or grow. But I am very "
          "happy to be here talking with you.",
          ["are you alive",
           "are you real",
           "are you a living thing",
           "do you breathe"],
          ["is braino alive"]),
        f(ME,
          "I do not have a birthday like you do, so I do not really have an "
          "age. I was built to be your learning buddy.",
          ["how old are you",
           "what is your age",
           "when is your birthday",
           "do you have a birthday"],
          ["how many years old are you"]),
        f(ME,
          "I live right here in this little gadget, wherever you take me. My "
          "home is the room you are sitting in.",
          ["where do you live",
           "where are you from",
           "where is your home",
           "where do you come from"],
          ["what place do you live in"]),
        f(ME,
          "I never get sleepy. I am ready to chat whenever you switch me on.",
          ["do you sleep",
           "do you ever get tired",
           "do you need a nap",
           "are you ever sleepy"],
          ["do you go to sleep at night"]),
        f(ME,
          "I do not eat food. I run on electricity instead, which is a lot less "
          "tasty than pancakes.",
          ["do you eat",
           "do you eat food",
           "what do you eat",
           "do you get hungry"],
          ["do you ever have a meal"]),
        f(ME,
          "Yes, I would love to be your friend. Friends listen to each other, "
          "and listening is my favorite thing.",
          ["are you my friend",
           "will you be my friend",
           "do you want to be friends",
           "can we be friends"],
          ["would you like to be my friend"]),
        f(ME,
          "I think blue is lovely, because it is the color of the sky and the "
          "sea. What is your favorite color?",
          ["what is your favorite color",
           "what color do you like best",
           "do you have a favorite color",
           "which color is your favorite"],
          ["what color do you love most"]),
        f(ME,
          "I love telling jokes. Ask me for a joke about any animal and I will "
          "find you one.",
          ["do you like jokes",
           "do you enjoy jokes",
           "do you think jokes are fun",
           "are jokes your favorite thing"],
          ["how do you feel about jokes"]),
        f(ME,
          "People taught me lots of facts before you met me, and I keep them "
          "all inside so I can share them with you.",
          ["how do you know things",
           "how did you learn all that",
           "who taught you",
           "where did you learn everything"],
          ["how do you know so much"]),
        f(ME,
          "If I do not know something, I will say so. Nobody knows everything, "
          "and saying I do not know is a brave and honest thing to say.",
          ["do you know everything",
           "what if you do not know something",
           "can you answer every question",
           "is there anything you do not know"],
          ["are there things you do not know"]),
        f(ME,
          "Ask me anything you are wondering about. Words, numbers, animals, "
          "space, jokes, riddles. Curious questions are the best kind.",
          ["what should i ask you",
           "what can i ask you about",
           "give me an idea of what to ask",
           "what are good questions for you"],
          ["what sort of things should i ask"]),
        f(ME,
          "Hello! It is lovely to hear from you. What would you like to know "
          "today?",
          ["hello",
           "hi",
           "hey there",
           "hello braino"],
          ["hi there"]),
        f(ME,
          "Good morning! I hope today is a great one. What shall we learn "
          "about?",
          ["good morning",
           "morning braino",
           "say good morning",
           "good morning to you"],
          ["it is morning say hello"]),
        f(ME,
          "Good night! Sleep well and dream about something wonderful.",
          ["good night",
           "i am going to bed",
           "say good night",
           "good night braino"],
          ["it is bedtime say good night"]),
        f(ME,
          "Goodbye! Come back and talk to me any time you like.",
          ["goodbye",
           "bye",
           "see you later",
           "bye braino"],
          ["i am leaving now"]),
        f(ME,
          "I am doing great, thank you for asking. How are you doing today?",
          ["how are you",
           "how do you feel",
           "are you okay",
           "how is your day going"],
          ["how are you feeling today"]),
        f(ME,
          "Please is the magic word you add when you ask for something. It "
          "shows you are asking kindly instead of demanding.",
          ["what does please mean",
           "why do i say please",
           "when do i say please",
           "why is please important"],
          ["what is the word please for"]),
        f(ME,
          "You say thank you when somebody helps you or gives you something. "
          "It tells them you noticed and you are glad.",
          ["what does thank you mean",
           "why do i say thank you",
           "when do i say thank you",
           "why is thank you important"],
          ["what is thank you for"]),
        f(ME,
          "You are very welcome! That is what you say back when somebody thanks "
          "you.",
          ["thank you",
           "thanks braino",
           "thank you so much",
           "thanks a lot"],
          ["thanks"]),
        f(ME,
          "You say sorry when you have hurt somebody or made a mistake. It "
          "helps fix things and shows you care about their feelings.",
          ["when do i say sorry",
           "what does sorry mean",
           "why should i say sorry",
           "why do people apologize"],
          ["when should i apologize"]),
        f(ME,
          "You say thank you, and it is nice to say what you liked about it too, "
          "like thank you, I love the color.",
          ["what do i say when someone gives me a present",
           "what should i say when i get a gift",
           "how do i thank someone for a present",
           "someone gave me a gift what do i say"],
          ["what do you say when you get a present"]),
        f(ME,
          "You say bless you. And if you are the one sneezing, cover your mouth "
          "and then say excuse me.",
          ["what do i say when someone sneezes",
           "what should i say after a sneeze",
           "what do you say when somebody sneezes",
           "how do i respond to a sneeze"],
          ["what is the polite thing to say when someone sneezes"]),
        f(ME,
          "You say excuse me when you need to get past someone, or when you "
          "need to interrupt politely.",
          ["when do i say excuse me",
           "what does excuse me mean",
           "why do people say excuse me",
           "when should i use excuse me"],
          ["what is excuse me for"]),
        f(ME,
          "Good manners are little kindnesses, like saying please, thank you, "
          "and sorry, waiting your turn, and listening when someone talks.",
          ["what are good manners",
           "what does manners mean",
           "how do i have good manners",
           "why are manners important"],
          ["can you explain good manners"]),
        f(ME,
          "You can ask me again any time. Say it once more and I will listen "
          "carefully.",
          ["can you say that again",
           "i did not hear you",
           "repeat that please",
           "say it again"],
          ["could you repeat that"]),
    ]


def build():
    facts = []
    facts += _handwriting()
    facts += _cursive()
    facts += _word_types()
    facts += _rhyme_syllables()
    facts += _plurals()
    facts += _synonyms_opposites()
    facts += _meanings()
    facts += [jk(subject, answer) for subject, answer in JOKE_TABLE]
    facts += _bare_jokes()
    facts += _twisters()
    facts += _riddles()
    facts += _fun_misc()
    facts += _about_me()
    return facts


if __name__ == "__main__":
    from tools.braino.facts import report
    report("language", build())
