"""Math concepts for a five to eight year old: fractions, percentages, roman
numerals, money, sudoku and logic, and telling time.

Every computable answer walks through the middle step out loud, because that is
what makes the model generalize to numbers it never saw in training. Roman
numerals are spelled as separate letters ("X I V") so the speech engine reads
them one letter at a time instead of trying to pronounce a word.
"""
from . import Fact, report


# --------------------------------------------------------------------------
# fractions
# --------------------------------------------------------------------------

def _fractions():
    T = "fractions"
    return [
        Fact(T,
             ["what is a fraction",
              "what does fraction mean",
              "can you tell me what a fraction is",
              "explain fractions to me"],
             "A fraction is a piece of a whole thing. If you cut something into equal pieces, each piece is a fraction. Half of an apple is a fraction of the apple.",
             ["what is a fraction in easy words"]),
        Fact(T,
             ["what is a half",
              "what does half mean",
              "tell me about halves",
              "what is one half"],
             "A half is one of two equal pieces. Cut a sandwich straight down the middle and each piece is a half. Two halves make the whole sandwich again.",
             ["if i cut something in half what do i get"]),
        Fact(T,
             ["what is a quarter",
              "what does quarter mean in fractions",
              "what is one quarter",
              "tell me about quarters"],
             "A quarter is one of four equal pieces. Cut a pizza into four equal slices and one slice is a quarter. Four quarters make the whole pizza.",
             ["what is a fourth of something"]),
        Fact(T,
             ["what is a third",
              "what does a third mean",
              "what is one third",
              "tell me about thirds"],
             "A third is one of three equal pieces. Share a chocolate bar fairly between three friends and each friend gets a third. Three thirds make the whole bar.",
             ["explain what one third is"]),
        Fact(T,
             ["how many halves make a whole",
              "how many halves in one whole",
              "how many halves do i need for a whole one",
              "how many halves make one"],
             "One whole splits into two equal pieces, and each piece is a half. So you need two halves to make one whole.",
             ["how many half pieces make a whole thing"]),
        Fact(T,
             ["how many quarters make a whole",
              "how many quarters in one whole",
              "how many quarters make one",
              "how many quarters do i need for a whole one"],
             "One whole splits into four equal pieces, and each piece is a quarter. So you need four quarters to make one whole.",
             ["how many quarter pieces make a whole thing"]),
        Fact(T,
             ["how many thirds make a whole",
              "how many thirds in one whole",
              "how many thirds make one",
              "how many thirds do i need for a whole one"],
             "One whole splits into three equal pieces, and each piece is a third. So you need three thirds to make one whole.",
             ["how many third pieces make a whole thing"]),
        Fact(T,
             ["what is the numerator",
              "what does numerator mean",
              "what is the top number of a fraction",
              "tell me about the numerator"],
             "The numerator is the top number of a fraction. It counts how many pieces you have. In three quarters the numerator is three, so you have three pieces.",
             ["which number in a fraction is the numerator"]),
        Fact(T,
             ["what is the denominator",
              "what does denominator mean",
              "what is the bottom number of a fraction",
              "tell me about the denominator"],
             "The denominator is the bottom number of a fraction. It tells how many equal pieces the whole was cut into. In three quarters the denominator is four.",
             ["which number in a fraction is the denominator"]),
        Fact(T,
             ["what does equal shares mean",
              "what are equal shares",
              "why do fraction pieces have to be equal",
              "do fraction pieces need to be the same size"],
             "Equal shares means every piece is the same size. If one piece is bigger, it is not a fair share and it is not a real half or quarter. Fractions are always fair pieces.",
             ["what makes a share fair in fractions"]),
        Fact(T,
             ["what is half of ten",
              "what is one half of ten",
              "half of ten is what",
              "tell me half of ten"],
             "Half means splitting into two equal groups. Ten splits into five and five. So half of ten is five.",
             ["if i share ten things between two people how many each"]),
        Fact(T,
             ["what is half of eight",
              "what is one half of eight",
              "half of eight is what",
              "tell me half of eight"],
             "Half means splitting into two equal groups. Eight splits into four and four. So half of eight is four.",
             ["if i share eight things between two people how many each"]),
        Fact(T,
             ["what is half of twenty",
              "what is one half of twenty",
              "half of twenty is what",
              "tell me half of twenty"],
             "Half means splitting into two equal groups. Twenty splits into ten and ten. So half of twenty is ten.",
             ["if i share twenty things between two people how many each"]),
        Fact(T,
             ["what is half of six",
              "what is one half of six",
              "half of six is what",
              "tell me half of six"],
             "Half means splitting into two equal groups. Six splits into three and three. So half of six is three.",
             ["if i share six things between two people how many each"]),
        Fact(T,
             ["what is half of one hundred",
              "what is one half of one hundred",
              "half of one hundred is what",
              "tell me half of a hundred"],
             "Half means splitting into two equal groups. One hundred splits into fifty and fifty. So half of one hundred is fifty.",
             ["if i share one hundred things between two people how many each"]),
        Fact(T,
             ["what is a quarter of twelve",
              "what is one quarter of twelve",
              "quarter of twelve is what",
              "tell me a quarter of twelve"],
             "A quarter means splitting into four equal groups. Twelve splits into three and three and three and three. So a quarter of twelve is three.",
             ["if i share twelve things between four people how many each"]),
        Fact(T,
             ["what is a quarter of eight",
              "what is one quarter of eight",
              "quarter of eight is what",
              "tell me a quarter of eight"],
             "A quarter means splitting into four equal groups. Eight splits into two and two and two and two. So a quarter of eight is two.",
             ["if i share eight things between four people how many each"]),
        Fact(T,
             ["what is a quarter of twenty",
              "what is one quarter of twenty",
              "quarter of twenty is what",
              "tell me a quarter of twenty"],
             "A quarter means splitting into four equal groups. Twenty splits into five and five and five and five. So a quarter of twenty is five.",
             ["if i share twenty things between four people how many each"]),
        Fact(T,
             ["what is a third of nine",
              "what is one third of nine",
              "third of nine is what",
              "tell me a third of nine"],
             "A third means splitting into three equal groups. Nine splits into three and three and three. So a third of nine is three.",
             ["if i share nine things between three people how many each"]),
        Fact(T,
             ["what is a third of twelve",
              "what is one third of twelve",
              "third of twelve is what",
              "tell me a third of twelve"],
             "A third means splitting into three equal groups. Twelve splits into four and four and four. So a third of twelve is four.",
             ["if i share twelve things between three people how many each"]),
        Fact(T,
             ["what is a third of six",
              "what is one third of six",
              "third of six is what",
              "tell me a third of six"],
             "A third means splitting into three equal groups. Six splits into two and two and two. So a third of six is two.",
             ["if i share six things between three people how many each"]),
        Fact(T,
             ["what is three quarters",
              "what does three quarters mean",
              "tell me about three quarters",
              "what is three fourths"],
             "Three quarters means three of the four equal pieces. Cut a pizza into four slices and take three of them. That is most of the pizza, with one slice left.",
             ["explain three quarters to me"]),
        Fact(T,
             ["what is three quarters of twelve",
              "what is three fourths of twelve",
              "three quarters of twelve is what",
              "tell me three quarters of twelve"],
             "One quarter of twelve is three, because twelve splits into four groups of three. Three quarters is three of those groups, and three plus three plus three is nine. So it is nine.",
             ["if i take three of the four equal parts of twelve what do i get"]),
        Fact(T,
             ["what is three quarters of eight",
              "what is three fourths of eight",
              "three quarters of eight is what",
              "tell me three quarters of eight"],
             "One quarter of eight is two, because eight splits into four groups of two. Three quarters is three of those groups, and two plus two plus two is six. So it is six.",
             ["if i take three of the four equal parts of eight what do i get"]),
        Fact(T,
             ["what is two thirds of nine",
              "two thirds of nine is what",
              "tell me two thirds of nine",
              "how much is two thirds of nine"],
             "One third of nine is three, because nine splits into three groups of three. Two thirds is two of those groups, and three plus three is six. So it is six.",
             ["if i take two of the three equal parts of nine what do i get"]),
        Fact(T,
             ["are two quarters the same as a half",
              "is two quarters equal to one half",
              "do two quarters make a half",
              "why is two quarters the same as a half"],
             "Cut a pizza into four slices and take two of them. That is the same amount as cutting it in two and taking one piece. So two quarters and one half are the same.",
             ["is a half the same size as two quarters"]),
        Fact(T,
             ["are two halves the same as a whole",
              "do two halves make a whole",
              "is two halves equal to one",
              "what do two halves add up to"],
             "One half plus one half puts both pieces back together. The two pieces fill the whole thing with nothing left over. So two halves make one whole.",
             ["if i put both halves together what do i have"]),
        Fact(T,
             ["are two fourths the same as two quarters",
              "is a fourth the same as a quarter",
              "do quarter and fourth mean the same thing",
              "why do people say fourth and quarter"],
             "A fourth and a quarter are two names for the same thing. Both mean one of four equal pieces. You can say either one and be right.",
             ["is one fourth another way to say one quarter"]),
        Fact(T,
             ["are three thirds the same as one whole",
              "do three thirds make a whole",
              "is three thirds equal to one",
              "what do three thirds add up to"],
             "Each third is one of three equal pieces. Put all three back together and nothing is missing. So three thirds make one whole.",
             ["if i put all three thirds together what do i have"]),
        Fact(T,
             ["which is bigger a half or a quarter",
              "is a half bigger than a quarter",
              "what is more one half or one quarter",
              "which piece is larger half or quarter"],
             "A half cuts the whole into two pieces and a quarter cuts it into four. Fewer cuts means bigger pieces. So a half is bigger than a quarter.",
             ["would you rather have half a cake or a quarter of it"]),
        Fact(T,
             ["which is bigger a half or a third",
              "is a half bigger than a third",
              "what is more one half or one third",
              "which piece is larger half or third"],
             "A half cuts the whole into two pieces and a third cuts it into three. Splitting into more pieces makes each one smaller. So a half is bigger than a third.",
             ["would you rather have half a bar or a third of it"]),
        Fact(T,
             ["why does a bigger bottom number mean smaller pieces",
              "why is a tenth smaller than a half",
              "does a bigger denominator mean a smaller piece",
              "why do more pieces mean smaller pieces"],
             "The bottom number says how many pieces the whole was cut into. Cutting a cake into ten pieces makes each one tiny. More pieces always means smaller pieces.",
             ["why is one tenth so small"]),
        Fact(T,
             ["what is half of six apples",
              "if i have six apples what is half of them",
              "half of a set of six apples",
              "how many apples is half of six apples"],
             "Half means two equal groups. Six apples split into a group of three and a group of three. So half of six apples is three apples.",
             ["i have six apples and share half of them how many is that"]),
        Fact(T,
             ["what is a quarter of a set of sixteen",
              "what is one quarter of sixteen",
              "quarter of sixteen is what",
              "tell me a quarter of sixteen"],
             "A quarter means four equal groups. Sixteen splits into four and four and four and four. So a quarter of sixteen is four.",
             ["if i share sixteen stickers between four kids how many each"]),
        Fact(T,
             ["can a fraction be part of a group of things",
              "can you have a fraction of a set",
              "what is a fraction of a set",
              "do fractions work on groups not just cakes"],
             "Yes. A fraction can share out a group too. Half of eight marbles means splitting eight marbles into two equal piles of four. Fractions work on anything you can share fairly.",
             ["can i take half of a pile of toys"]),
        Fact(T,
             ["what does the line in a fraction mean",
              "why is there a line in a fraction",
              "what is the fraction line for",
              "what does the bar in a fraction do"],
             "The line means shared into. The number under the line is how many pieces the whole was cut into, and the number above it is how many of those pieces you have.",
             ["what is the line between the two fraction numbers"]),
    ]


# --------------------------------------------------------------------------
# percentages
# --------------------------------------------------------------------------

def _percentages():
    T = "percentages"
    return [
        Fact(T,
             ["what does percent mean",
              "what is a percent",
              "what does percentage mean",
              "explain percent to me"],
             "Percent means out of every hundred. If ten percent of the candies are red, that means ten red candies out of every hundred candies.",
             ["what is a percentage in easy words"]),
        Fact(T,
             ["what does the percent sign mean",
              "what is that little circle sign for percent",
              "what symbol means percent",
              "what does the percent symbol stand for"],
             "The percent sign is a short way to write out of a hundred. Instead of saying fifty out of a hundred, people write fifty and the percent sign next to it.",
             ["why do people use a percent sign"]),
        Fact(T,
             ["what does one hundred percent mean",
              "what is one hundred percent",
              "what does a hundred percent mean",
              "if something is one hundred percent what does that mean"],
             "One hundred percent means a hundred out of a hundred, which is every single one. It means all of it, the whole thing, nothing missing.",
             ["is one hundred percent all of something"]),
        Fact(T,
             ["what does zero percent mean",
              "what is zero percent",
              "if something is zero percent what does that mean",
              "what does no percent mean"],
             "Zero percent means zero out of a hundred, which is none at all. A battery at zero percent has no power left in it.",
             ["does zero percent mean nothing is left"]),
        Fact(T,
             ["what does fifty percent mean",
              "what is fifty percent",
              "is fifty percent the same as half",
              "what fraction is fifty percent"],
             "Fifty percent means fifty out of every hundred. Fifty is half of a hundred, so fifty percent is just another way of saying half.",
             ["what everyday amount is fifty percent"]),
        Fact(T,
             ["what does twenty five percent mean",
              "what is twenty five percent",
              "is twenty five percent the same as a quarter",
              "what fraction is twenty five percent"],
             "Twenty-five percent means twenty-five out of every hundred. Twenty-five is a quarter of a hundred, so twenty-five percent is another way of saying a quarter.",
             ["what everyday amount is twenty five percent"]),
        Fact(T,
             ["what does ten percent mean",
              "what is ten percent",
              "is ten percent the same as a tenth",
              "what fraction is ten percent"],
             "Ten percent means ten out of every hundred. Ten fits into a hundred ten times, so ten percent is the same as one tenth, a small slice of the whole.",
             ["what everyday amount is ten percent"]),
        Fact(T,
             ["what does seventy five percent mean",
              "what is seventy five percent",
              "is seventy five percent the same as three quarters",
              "what fraction is seventy five percent"],
             "Seventy-five percent means seventy-five out of every hundred. That is three quarters of a hundred, so seventy-five percent is the same as three quarters.",
             ["what everyday amount is seventy five percent"]),
        Fact(T,
             ["what is fifty percent of twenty",
              "fifty percent of twenty is what",
              "tell me fifty percent of twenty",
              "how much is fifty percent of twenty"],
             "Fifty percent means half. Half of twenty is ten, because twenty splits into ten and ten. So fifty percent of twenty is ten.",
             ["if twenty things are cut by fifty percent how many is that"]),
        Fact(T,
             ["what is fifty percent of ten",
              "fifty percent of ten is what",
              "tell me fifty percent of ten",
              "how much is fifty percent of ten"],
             "Fifty percent means half. Half of ten is five, because ten splits into five and five. So fifty percent of ten is five.",
             ["how much is half of ten in percent talk"]),
        Fact(T,
             ["what is fifty percent of one hundred",
              "fifty percent of one hundred is what",
              "tell me fifty percent of one hundred",
              "how much is fifty percent of a hundred"],
             "Fifty percent means half. Half of one hundred is fifty, because a hundred splits into fifty and fifty. So fifty percent of one hundred is fifty.",
             ["how much is half of a hundred in percent talk"]),
        Fact(T,
             ["what is fifty percent of forty",
              "fifty percent of forty is what",
              "tell me fifty percent of forty",
              "how much is fifty percent of forty"],
             "Fifty percent means half. Half of forty is twenty, because forty splits into twenty and twenty. So fifty percent of forty is twenty.",
             ["if i take half of forty how much is that"]),
        Fact(T,
             ["what is twenty five percent of one hundred",
              "twenty five percent of one hundred is what",
              "tell me twenty five percent of one hundred",
              "how much is twenty five percent of a hundred"],
             "Twenty-five percent means a quarter. A quarter of one hundred is twenty-five, because a hundred splits into four groups of twenty-five. So the answer is twenty-five.",
             ["what is a quarter of a hundred in percent talk"]),
        Fact(T,
             ["what is twenty five percent of twenty",
              "twenty five percent of twenty is what",
              "tell me twenty five percent of twenty",
              "how much is twenty five percent of twenty"],
             "Twenty-five percent means a quarter. A quarter of twenty is five, because twenty splits into four groups of five. So twenty-five percent of twenty is five.",
             ["what is a quarter of twenty in percent talk"]),
        Fact(T,
             ["what is twenty five percent of eight",
              "twenty five percent of eight is what",
              "tell me twenty five percent of eight",
              "how much is twenty five percent of eight"],
             "Twenty-five percent means a quarter. A quarter of eight is two, because eight splits into four groups of two. So twenty-five percent of eight is two.",
             ["what is a quarter of eight in percent talk"]),
        Fact(T,
             ["what is ten percent of fifty",
              "ten percent of fifty is what",
              "tell me ten percent of fifty",
              "how much is ten percent of fifty"],
             "Ten percent means ten out of every hundred, which is one tenth. A tenth of fifty is five, because fifty splits into ten groups of five. So it is five.",
             ["how much is a tenth of fifty"]),
        Fact(T,
             ["what is ten percent of one hundred",
              "ten percent of one hundred is what",
              "tell me ten percent of one hundred",
              "how much is ten percent of a hundred"],
             "Ten percent means ten out of every hundred. There is exactly one hundred here, so you get one lot of ten. So ten percent of one hundred is ten.",
             ["how much is a tenth of a hundred"]),
        Fact(T,
             ["what is ten percent of twenty",
              "ten percent of twenty is what",
              "tell me ten percent of twenty",
              "how much is ten percent of twenty"],
             "Ten percent is one tenth. Twenty splits into ten groups of two. One of those groups is two. So ten percent of twenty is two.",
             ["how much is a tenth of twenty"]),
        Fact(T,
             ["what is ten percent of thirty",
              "ten percent of thirty is what",
              "tell me ten percent of thirty",
              "how much is ten percent of thirty"],
             "Ten percent is one tenth. Thirty splits into ten groups of three. One of those groups is three. So ten percent of thirty is three.",
             ["how much is a tenth of thirty"]),
        Fact(T,
             ["what is ten percent of sixty",
              "ten percent of sixty is what",
              "tell me ten percent of sixty",
              "how much is ten percent of sixty"],
             "Ten percent is one tenth. Sixty splits into ten groups of six. One of those groups is six. So ten percent of sixty is six.",
             ["how much is a tenth of sixty"]),
        Fact(T,
             ["what is twenty percent of one hundred",
              "twenty percent of one hundred is what",
              "tell me twenty percent of one hundred",
              "how much is twenty percent of a hundred"],
             "Twenty percent means twenty out of every hundred. There is one hundred here, so you get one lot of twenty. So twenty percent of one hundred is twenty.",
             ["if i take twenty percent of a hundred what do i get"]),
        Fact(T,
             ["what is twenty percent of ten",
              "twenty percent of ten is what",
              "tell me twenty percent of ten",
              "how much is twenty percent of ten"],
             "Ten percent of ten is one, because ten splits into ten groups of one. Twenty percent is two of those groups, and one plus one is two. So the answer is two.",
             ["if i take twenty percent of ten what do i get"]),
        Fact(T,
             ["what is seventy five percent of one hundred",
              "seventy five percent of one hundred is what",
              "tell me seventy five percent of one hundred",
              "how much is seventy five percent of a hundred"],
             "Seventy-five percent means three quarters. A quarter of one hundred is twenty-five, and three of those is twenty-five plus twenty-five plus twenty-five, which is seventy-five.",
             ["how much is three quarters of a hundred"]),
        Fact(T,
             ["what is seventy five percent of twenty",
              "seventy five percent of twenty is what",
              "tell me seventy five percent of twenty",
              "how much is seventy five percent of twenty"],
             "Seventy-five percent means three quarters. A quarter of twenty is five, and three of those is five plus five plus five, which is fifteen. So the answer is fifteen.",
             ["how much is three quarters of twenty"]),
        Fact(T,
             ["which is more twenty five percent or fifty percent",
              "is fifty percent bigger than twenty five percent",
              "what is larger twenty five percent or fifty percent",
              "which percent is bigger fifty or twenty five"],
             "Twenty-five percent is twenty-five out of a hundred and fifty percent is fifty out of a hundred. Fifty is more than twenty-five. So fifty percent is bigger.",
             ["would you rather have fifty percent or twenty five percent of a cake"]),
        Fact(T,
             ["which is more ten percent or one hundred percent",
              "is one hundred percent bigger than ten percent",
              "what is larger ten percent or a hundred percent",
              "which percent is bigger a hundred or ten"],
             "Ten percent is ten out of a hundred, just a small slice. One hundred percent is all one hundred. So one hundred percent is much bigger.",
             ["is all of something more than ten percent of it"]),
        Fact(T,
             ["what does it mean when my battery says fifty percent",
              "what does fifty percent battery mean",
              "my tablet battery is at fifty percent what does that mean",
              "if the battery shows fifty percent how full is it"],
             "Your battery is half full. Fifty out of every hundred bits of power are still there, so about half the playing time is left before it needs charging.",
             ["how full is a battery at fifty percent"]),
        Fact(T,
             ["what does it mean when my battery says ten percent",
              "what does ten percent battery mean",
              "my tablet battery is at ten percent what does that mean",
              "if the battery shows ten percent how full is it"],
             "Only ten out of every hundred bits of power are left, which is a tenth of a full battery. That is nearly empty, so it is time to plug it in.",
             ["is ten percent battery a lot or a little"]),
        Fact(T,
             ["what does one hundred percent battery mean",
              "if my battery says one hundred percent is it full",
              "what does a full battery percent look like",
              "when is a battery all charged up"],
             "One hundred percent means all one hundred out of a hundred bits of power are there. The battery is completely full and ready to go.",
             ["does one hundred percent mean fully charged"]),
        Fact(T,
             ["what does fifty percent off mean in a shop",
              "what does half off mean in a store",
              "if a toy is fifty percent off what happens",
              "what is a fifty percent sale"],
             "Fifty percent off means the price is cut in half. A toy that cost ten dollars would come down to five dollars, because half of ten is five.",
             ["if a ten dollar toy is fifty percent off what does it cost"]),
        Fact(T,
             ["what does ten percent off mean in a shop",
              "what is a ten percent discount",
              "if something is ten percent off what happens",
              "what does a ten percent sale mean"],
             "Ten percent off means you take away one tenth of the price. On a twenty dollar game, a tenth is two dollars, so you pay eighteen dollars instead.",
             ["if a twenty dollar game is ten percent off what does it cost"]),
        Fact(T,
             ["why do shops use percent",
              "why are sales written in percent",
              "why do stores say percent off",
              "what is percent used for in stores"],
             "Percent lets one number work for every price. Ten percent off means a tenth off a cheap thing and a tenth off an expensive thing, so one sign covers the whole store.",
             ["why is percent handy for prices"]),
        Fact(T,
             ["where do i see percent in real life",
              "where are percentages used",
              "what things show percentages",
              "when would i notice a percent"],
             "You see percent on battery bars, on sale signs in shops, on test scores at school, and in weather reports that say the chance of rain.",
             ["name some places percentages show up"]),
        Fact(T,
             ["how is percent like a fraction",
              "are percent and fractions the same thing",
              "how do percents and fractions connect",
              "can a percent be written as a fraction"],
             "A percent is a fraction with a hundred on the bottom. Fifty percent is fifty out of a hundred, which is the same as a half. They are two ways to say one amount.",
             ["what fraction is hiding inside a percent"]),
    ]


# --------------------------------------------------------------------------
# roman numerals
# --------------------------------------------------------------------------

def _roman():
    T = "roman numerals"
    facts = [
        Fact(T,
             ["what are roman numerals",
              "what is a roman numeral",
              "tell me about roman numerals",
              "explain roman numerals"],
             "Roman numerals are numbers written with letters instead of digits. The ancient Romans used them, and we still see them on clocks and in books today.",
             ["what does roman numeral mean"]),
        Fact(T,
             ["what letters are used in roman numerals",
              "which letters are roman numerals",
              "what are all the roman numeral letters",
              "list the roman numeral letters"],
             "There are seven letters. I is one, V is five, X is ten, L is fifty, C is one hundred, D is five hundred, and M is one thousand.",
             ["how many different letters do roman numerals use"]),
        Fact(T,
             ["what does the letter i mean in roman numerals",
              "what number is the roman letter i",
              "what is i worth in roman numerals",
              "how much is the roman numeral i"],
             "The letter I stands for one. Write it twice for two and three times for three, so three is I I I.",
             ["what is the value of i in roman numbers"]),
        Fact(T,
             ["what does the letter v mean in roman numerals",
              "what number is the roman letter v",
              "what is v worth in roman numerals",
              "how much is the roman numeral v"],
             "The letter V stands for five. Some people say it looks like a hand with five fingers spread into a V shape.",
             ["what is the value of v in roman numbers"]),
        Fact(T,
             ["what does the letter x mean in roman numerals",
              "what number is the roman letter x",
              "what is x worth in roman numerals",
              "how much is the roman numeral x"],
             "The letter X stands for ten. It looks like two V shapes stacked together, and five plus five is ten.",
             ["what is the value of x in roman numbers"]),
        Fact(T,
             ["what does the letter l mean in roman numerals",
              "what number is the roman letter l",
              "what is l worth in roman numerals",
              "how much is the roman numeral l"],
             "The letter L stands for fifty. Fifty is half of one hundred, so L sits halfway between X and C.",
             ["what is the value of l in roman numbers"]),
        Fact(T,
             ["what does the letter c mean in roman numerals",
              "what number is the roman letter c",
              "what is c worth in roman numerals",
              "how much is the roman numeral c"],
             "The letter C stands for one hundred. It helps to remember that century means a hundred years, and century starts with C.",
             ["what is the value of c in roman numbers"]),
        Fact(T,
             ["what does the letter d mean in roman numerals",
              "what number is the roman letter d",
              "what is d worth in roman numerals",
              "how much is the roman numeral d"],
             "The letter D stands for five hundred. That is half of one thousand.",
             ["what is the value of d in roman numbers"]),
        Fact(T,
             ["what does the letter m mean in roman numerals",
              "what number is the roman letter m",
              "what is m worth in roman numerals",
              "how much is the roman numeral m"],
             "The letter M stands for one thousand. Remember it with the word millennium, which means a thousand years.",
             ["what is the value of m in roman numbers"]),
        Fact(T,
             ["why is there no zero in roman numerals",
              "do roman numerals have a zero",
              "is there a roman numeral for zero",
              "how do you write zero in roman numerals"],
             "There is no zero. The Romans used numerals for counting things like sheep and soldiers, and you never need to count none of something, so they never made a symbol for it.",
             ["why did the romans not write zero"]),
        Fact(T,
             ["what is the subtraction rule in roman numerals",
              "why is four written with an i before a v",
              "what does it mean when a smaller letter comes first",
              "how does the take away rule work in roman numerals"],
             "When a smaller letter sits in front of a bigger one, you take it away instead of adding. I before V means one before five, which is four.",
             ["what happens when a small roman letter goes before a big one"]),
        Fact(T,
             ["how do you read roman numerals",
              "how do i work out a roman numeral",
              "what is the trick for reading roman numerals",
              "how do you add up roman numeral letters"],
             "Read from left to right and add the letters up. If a smaller letter comes before a bigger one, take it away instead. So X I is eleven and I X is nine.",
             ["what is the rule for adding up roman letters"]),
        Fact(T,
             ["where do we still see roman numerals",
              "where are roman numerals used today",
              "what things use roman numerals",
              "do people still use roman numerals"],
             "You can spot them on fancy clock faces, on chapter pages at the front of books, at the end of movies for the year, and after king and queen names.",
             ["where would i find roman numerals nowadays"]),
        Fact(T,
             ["why are roman numerals on clocks",
              "do clocks use roman numerals",
              "what roman numerals are on a clock face",
              "why does grandpa's clock have letters instead of numbers"],
             "Old fashioned clock faces use roman numerals because they look elegant. They run from I at one o'clock all the way round to X I I at twelve o'clock.",
             ["which roman numeral sits at the top of a clock"]),
        Fact(T,
             ["why are roman numerals in books",
              "why do books have roman numerals at the front",
              "what are roman numeral page numbers for",
              "why are some page numbers letters"],
             "The pages before the story starts, like the contents, are often numbered with roman numerals. That way the real story can still begin on page one.",
             ["why do the first pages of a book use letters"]),
        Fact(T,
             ["why are roman numerals in film credits",
              "why do movies use roman numerals at the end",
              "what are the letters at the end of a movie",
              "why is the year of a film in roman numerals"],
             "At the very end of a movie the year it was made is often written in roman numerals. It looks grand, and it makes an old film feel less old.",
             ["what do the letters after a movie mean"]),
        Fact(T,
             ["why do kings and queens have roman numerals",
              "what do the numerals after a king's name mean",
              "why is there a numeral after a queen's name",
              "what does the numeral in a royal name mean"],
             "The numeral counts how many rulers have shared that name. A king called Henry the eighth is written Henry V I I I, meaning he was the eighth Henry.",
             ["why is there a letter after a royal name"]),
    ]

    # number -> numeral, with the reasoning shown
    spoken = {
        1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
        7: "seven", 8: "eight", 9: "nine", 10: "ten", 11: "eleven",
        12: "twelve", 13: "thirteen", 14: "fourteen", 15: "fifteen",
        16: "sixteen", 17: "seventeen", 18: "eighteen", 19: "nineteen",
        20: "twenty", 21: "twenty one", 24: "twenty four", 25: "twenty five",
        29: "twenty nine", 30: "thirty", 35: "thirty five", 39: "thirty nine",
        40: "forty", 50: "fifty", 100: "one hundred", 500: "five hundred",
        1000: "one thousand",
    }
    written = {
        1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
        7: "seven", 8: "eight", 9: "nine", 10: "ten", 11: "eleven",
        12: "twelve", 13: "thirteen", 14: "fourteen", 15: "fifteen",
        16: "sixteen", 17: "seventeen", 18: "eighteen", 19: "nineteen",
        20: "twenty", 21: "twenty-one", 24: "twenty-four", 25: "twenty-five",
        29: "twenty-nine", 30: "thirty", 35: "thirty-five", 39: "thirty-nine",
        40: "forty", 50: "fifty", 100: "one hundred", 500: "five hundred",
        1000: "one thousand",
    }
    numeral = {
        1: "I", 2: "II", 3: "III", 4: "IV", 5: "V", 6: "VI", 7: "VII",
        8: "VIII", 9: "IX", 10: "X", 11: "XI", 12: "XII", 13: "XIII",
        14: "XIV", 15: "XV", 16: "XVI", 17: "XVII", 18: "XVIII", 19: "XIX",
        20: "XX", 21: "XXI", 24: "XXIV", 25: "XXV", 29: "XXIX", 30: "XXX",
        35: "XXXV", 39: "XXXIX", 40: "XL", 50: "L", 100: "C", 500: "D",
        1000: "M",
    }
    # the middle step, said out loud
    work = {
        1: "One is the single letter I.",
        2: "Two is one and one, so you write I twice.",
        3: "Three is one and one and one, so you write I three times.",
        4: "Four is one before five. One is I and five is V, so I goes in front of V.",
        5: "Five has its own letter, V.",
        6: "Six is five and one more, so V comes first and then I.",
        7: "Seven is five and two more, so V comes first and then two I letters.",
        8: "Eight is five and three more, so V comes first and then three I letters.",
        9: "Nine is one before ten. One is I and ten is X, so I goes in front of X.",
        10: "Ten has its own letter, X.",
        11: "Eleven is ten and one more, so X comes first and then I.",
        12: "Twelve is ten and two more, so X comes first and then two I letters.",
        13: "Thirteen is ten and three more, so X then three I letters.",
        14: "Fourteen is ten and four more. Ten is X and four is I V, so put them together.",
        15: "Fifteen is ten and five more, so X then V.",
        16: "Sixteen is ten and five and one, so X then V then I.",
        17: "Seventeen is ten and five and two, so X then V then two I letters.",
        18: "Eighteen is ten and five and three, so X then V then three I letters.",
        19: "Nineteen is ten and nine more. Ten is X and nine is I X, so put them together.",
        20: "Twenty is ten and ten, so you write X twice.",
        21: "Twenty-one is twenty and one. Twenty is X X, then add I.",
        24: "Twenty-four is twenty and four. Twenty is X X and four is I V.",
        25: "Twenty-five is twenty and five. Twenty is X X, then add V.",
        29: "Twenty-nine is twenty and nine. Twenty is X X and nine is I X.",
        30: "Thirty is ten and ten and ten, so you write X three times.",
        35: "Thirty-five is thirty and five. Thirty is X X X, then add V.",
        39: "Thirty-nine is thirty and nine. Thirty is X X X and nine is I X.",
        40: "Forty is ten before fifty. Ten is X and fifty is L, so X goes in front of L.",
        50: "Fifty has its own letter, L.",
        100: "One hundred has its own letter, C, like the word century.",
        500: "Five hundred has its own letter, D.",
        1000: "One thousand has its own letter, M, like the word millennium.",
    }

    for n in spoken:
        s = spoken[n]
        w = written[n]
        letters = " ".join(numeral[n])
        facts.append(Fact(
            T,
            [f"what is {s} in roman numerals",
             f"how do you write {s} in roman numerals",
             f"what is the roman numeral for {s}",
             f"write {s} as a roman numeral"],
            f"{work[n]} So {w} is {letters}.",
            [f"show me {s} in roman numbers"]))

    # numeral -> number, the other direction
    for n in [4, 9, 11, 14, 19, 21, 24, 29, 39, 40, 50, 100, 1000]:
        letters = " ".join(numeral[n])
        spaced = " ".join(numeral[n].lower())
        w = written[n]
        facts.append(Fact(
            T,
            [f"what number is {spaced}",
             f"what does the roman numeral {spaced} mean",
             f"how much is {spaced} in roman numerals",
             f"read the roman numeral {spaced} for me"],
            f"{work[n]} So the numeral {letters} means {w}.",
            [f"tell me what {spaced} adds up to"]))

    return facts


# --------------------------------------------------------------------------
# money
# --------------------------------------------------------------------------

def _money():
    T = "money"
    return [
        Fact(T,
             ["what is money for",
              "why do we use money",
              "what do people use money for",
              "what is the point of money"],
             "Money is what people trade for things they need and want. You give the shop money and the shop gives you food, clothes, or a toy.",
             ["why do we need money at all"]),
        Fact(T,
             ["where does money come from",
              "how do people get money",
              "how do grown ups get money",
              "how do you earn money"],
             "Most grown ups earn money by doing a job. Kids can earn a little by helping with chores or getting it as a gift for a birthday.",
             ["how does a person get money to spend"]),
        Fact(T,
             ["what is a penny worth",
              "how much is a penny",
              "what is the value of a penny",
              "how many cents is a penny"],
             "A penny is worth one cent. It is the smallest coin in value, and it is the brown one.",
             ["how many cents does one penny make"]),
        Fact(T,
             ["what is a nickel worth",
              "how much is a nickel",
              "what is the value of a nickel",
              "how many cents is a nickel"],
             "A nickel is worth five cents. It is thicker than a dime even though a dime is worth more.",
             ["how many cents does one nickel make"]),
        Fact(T,
             ["what is a dime worth",
              "how much is a dime",
              "what is the value of a dime",
              "how many cents is a dime"],
             "A dime is worth ten cents. It is the smallest coin in size but it beats both the penny and the nickel.",
             ["how many cents does one dime make"]),
        Fact(T,
             ["what is a quarter worth",
              "how much is a quarter coin",
              "what is the value of a quarter",
              "how many cents is a quarter"],
             "A quarter is worth twenty-five cents. It is called a quarter because twenty-five cents is a quarter of a dollar.",
             ["how many cents does one quarter make"]),
        Fact(T,
             ["how many cents are in a dollar",
              "how many cents make one dollar",
              "how many cents is a dollar",
              "what is a dollar in cents"],
             "One dollar is one hundred cents. That is why a coin worth twenty-five cents is called a quarter, since twenty-five is a quarter of a hundred.",
             ["how many cents add up to a dollar"]),
        Fact(T,
             ["how many pennies make a dime",
              "how many pennies are in a dime",
              "how many pennies equal one dime",
              "how many one cent coins make a dime"],
             "A penny is one cent and a dime is ten cents. You need ten ones to reach ten. So ten pennies make one dime.",
             ["how many pennies do i swap for a dime"]),
        Fact(T,
             ["how many pennies make a dollar",
              "how many pennies are in a dollar",
              "how many pennies equal one dollar",
              "how many one cent coins make a dollar"],
             "A penny is one cent and a dollar is one hundred cents. Counting by ones up to one hundred takes a hundred coins. So one hundred pennies make a dollar.",
             ["how many pennies do i swap for a dollar"]),
        Fact(T,
             ["how many nickels make a quarter",
              "how many nickels are in a quarter",
              "how many nickels equal one quarter",
              "how many five cent coins make a quarter"],
             "A nickel is five cents and a quarter is twenty-five cents. Count by fives to twenty-five and that is five hops. So five nickels make a quarter.",
             ["how many nickels do i swap for a quarter"]),
        Fact(T,
             ["how many dimes make a dollar",
              "how many dimes are in a dollar",
              "how many dimes equal one dollar",
              "how many ten cent coins make a dollar"],
             "A dime is ten cents and a dollar is one hundred cents. Count by tens to one hundred and that is ten hops. So ten dimes make a dollar.",
             ["how many dimes do i swap for a dollar"]),
        Fact(T,
             ["how many quarters make a dollar",
              "how many quarters are in a dollar",
              "how many quarters equal one dollar",
              "how many twenty five cent coins make a dollar"],
             "A quarter is twenty-five cents. Twenty-five and twenty-five is fifty, and another two make one hundred. So four quarters make one dollar.",
             ["how many quarters do i swap for a dollar"]),
        Fact(T,
             ["how many nickels make a dime",
              "how many nickels are in a dime",
              "how many nickels equal one dime",
              "how many five cent coins make a dime"],
             "A nickel is five cents and a dime is ten cents. Five plus five is ten. So two nickels make one dime.",
             ["how many nickels do i swap for a dime"]),
        Fact(T,
             ["what money notes are there",
              "what dollar bills are there",
              "what paper money do people use",
              "what sizes of dollar bills exist"],
             "Common paper money comes as one dollar, five dollars, ten dollars, twenty dollars, fifty dollars, and one hundred dollars.",
             ["name some paper money amounts"]),
        Fact(T,
             ["what is the difference between coins and notes",
              "why is some money paper and some metal",
              "what is the difference between a coin and a bill",
              "why do we have both coins and paper money"],
             "Coins are metal and are used for small amounts like cents. Paper bills are used for bigger amounts like dollars, because carrying a hundred coins would be heavy.",
             ["why not make all money out of metal"]),
        Fact(T,
             ["what does making change mean",
              "what is change in money",
              "why does the shop give me change",
              "what does getting change mean"],
             "Change is the money you get back when you hand over more than the price. If you pay with a dollar for something cheaper, the shop gives back the difference.",
             ["what is the money i get back called"]),
        Fact(T,
             ["if something costs sixty two cents and i pay one dollar what is my change",
              "what change do i get from a dollar for sixty two cents",
              "i paid a dollar for a sixty two cent item how much change",
              "how much change from one dollar if the price is sixty two cents"],
             "The price is sixty-two cents. A dollar is one hundred cents. One hundred take away sixty-two leaves thirty-eight cents. So your change is thirty-eight cents.",
             ["a dollar minus sixty two cents leaves how much"]),
        Fact(T,
             ["if something costs seventy five cents and i pay one dollar what is my change",
              "what change do i get from a dollar for seventy five cents",
              "i paid a dollar for a seventy five cent item how much change",
              "how much change from one dollar if the price is seventy five cents"],
             "The price is seventy-five cents. A dollar is one hundred cents. One hundred take away seventy-five leaves twenty-five cents. So your change is twenty-five cents.",
             ["a dollar minus seventy five cents leaves how much"]),
        Fact(T,
             ["if something costs forty cents and i pay one dollar what is my change",
              "what change do i get from a dollar for forty cents",
              "i paid a dollar for a forty cent item how much change",
              "how much change from one dollar if the price is forty cents"],
             "The price is forty cents. A dollar is one hundred cents. One hundred take away forty leaves sixty cents. So your change is sixty cents.",
             ["a dollar minus forty cents leaves how much"]),
        Fact(T,
             ["if something costs ninety cents and i pay one dollar what is my change",
              "what change do i get from a dollar for ninety cents",
              "i paid a dollar for a ninety cent item how much change",
              "how much change from one dollar if the price is ninety cents"],
             "The price is ninety cents. A dollar is one hundred cents. One hundred take away ninety leaves ten cents. So your change is ten cents.",
             ["a dollar minus ninety cents leaves how much"]),
        Fact(T,
             ["if something costs three dollars and i pay five dollars what is my change",
              "what change do i get from five dollars for a three dollar item",
              "i paid five dollars for something that cost three how much change",
              "how much change from five dollars if the price is three dollars"],
             "The price is three dollars and you handed over five dollars. Five take away three leaves two. So your change is two dollars.",
             ["five dollars minus three dollars leaves how much"]),
        Fact(T,
             ["if something costs seven dollars and i pay ten dollars what is my change",
              "what change do i get from ten dollars for a seven dollar item",
              "i paid ten dollars for something that cost seven how much change",
              "how much change from ten dollars if the price is seven dollars"],
             "The price is seven dollars and you handed over ten dollars. Ten take away seven leaves three. So your change is three dollars.",
             ["ten dollars minus seven dollars leaves how much"]),
        Fact(T,
             ["if something costs twelve dollars and i pay twenty dollars what is my change",
              "what change do i get from twenty dollars for a twelve dollar item",
              "i paid twenty dollars for something that cost twelve how much change",
              "how much change from twenty dollars if the price is twelve dollars"],
             "The price is twelve dollars and you handed over twenty dollars. Twenty take away twelve leaves eight. So your change is eight dollars.",
             ["twenty dollars minus twelve dollars leaves how much"]),
        Fact(T,
             ["how can i make twenty five cents with coins",
              "what coins add up to twenty five cents",
              "show me different ways to make twenty five cents",
              "how do i make twenty five cents in different ways"],
             "One quarter is twenty-five cents all by itself. Or five nickels, since five fives make twenty-five. Or two dimes and one nickel, since ten and ten and five is twenty-five.",
             ["name a few ways to make twenty five cents"]),
        Fact(T,
             ["how can i make fifty cents with coins",
              "what coins add up to fifty cents",
              "show me different ways to make fifty cents",
              "how do i make fifty cents in different ways"],
             "Two quarters make fifty cents, since twenty-five and twenty-five is fifty. Or five dimes, since five tens make fifty. Or ten nickels, since ten fives make fifty.",
             ["name a few ways to make fifty cents"]),
        Fact(T,
             ["how can i make one dollar with coins",
              "what coins add up to one dollar",
              "show me different ways to make a dollar",
              "how do i make one dollar in different ways"],
             "Four quarters make a dollar, since twenty-five four times is one hundred. Or ten dimes, since ten tens is one hundred. Or twenty nickels, since twenty fives is one hundred.",
             ["name a few ways to make a dollar"]),
        Fact(T,
             ["can the same amount be made with different coins",
              "is there more than one way to make an amount",
              "why can i pay the same price with different coins",
              "do different coin piles ever equal the same money"],
             "Yes. What matters is the total, not which coins you use. Two dimes and a nickel is twenty-five cents, and so is one quarter. Both are worth the same.",
             ["can two different sets of coins be worth the same"]),
        Fact(T,
             ["how much is two quarters and one dime",
              "what do two quarters and a dime add up to",
              "add two quarters and one dime for me",
              "how many cents is two quarters plus a dime"],
             "Each quarter is twenty-five cents, so two quarters is fifty cents. A dime adds ten more. Fifty plus ten is sixty. So it is sixty cents.",
             ["i have two quarters and a dime how much money is that"]),
        Fact(T,
             ["how much is three dimes and two nickels",
              "what do three dimes and two nickels add up to",
              "add three dimes and two nickels for me",
              "how many cents is three dimes plus two nickels"],
             "Three dimes is ten and ten and ten, which is thirty cents. Two nickels is five and five, which is ten cents. Thirty plus ten is forty. So it is forty cents.",
             ["i have three dimes and two nickels how much money is that"]),
        Fact(T,
             ["how much is one quarter and three pennies",
              "what do a quarter and three pennies add up to",
              "add one quarter and three pennies for me",
              "how many cents is a quarter plus three pennies"],
             "A quarter is twenty-five cents. Three pennies add three more. Twenty-five plus three is twenty-eight. So it is twenty-eight cents.",
             ["i have a quarter and three pennies how much money is that"]),
        Fact(T,
             ["which costs more a toy for five dollars or one for eight dollars",
              "is eight dollars more than five dollars",
              "which is more expensive five dollars or eight dollars",
              "which price is bigger five dollars or eight dollars"],
             "Line the numbers up and compare. Eight is more than five. So the eight dollar toy costs more, and the five dollar one is the cheaper choice.",
             ["which toy is cheaper the five dollar one or the eight dollar one"]),
        Fact(T,
             ["what does cheaper mean",
              "what does it mean if something is cheaper",
              "what is a cheaper price",
              "what does cheap mean when shopping"],
             "Cheaper means it costs less money. If one apple is fifty cents and another is thirty cents, the thirty cent one is cheaper because thirty is less than fifty.",
             ["if something costs less what do we call it"]),
        Fact(T,
             ["what does expensive mean",
              "what does it mean if something is expensive",
              "what is an expensive price",
              "what makes a thing expensive"],
             "Expensive means it costs a lot of money. A bike is expensive next to a pencil, because you need many more dollars to buy it.",
             ["if something costs a lot what do we call it"]),
        Fact(T,
             ["can i buy a six dollar toy with four dollars",
              "do i have enough with four dollars for a six dollar toy",
              "is four dollars enough for something that costs six dollars",
              "can i afford a six dollar toy if i have four dollars"],
             "The toy costs six dollars and you have four. Six take away four leaves two. So you are two dollars short and need to save a bit more.",
             ["i have four dollars and want a six dollar toy what now"]),
        Fact(T,
             ["what does saving money mean",
              "what is saving up",
              "why do people save money",
              "what does it mean to save money"],
             "Saving means keeping money instead of spending it right away. A little bit each week grows into enough for something bigger later on.",
             ["what happens when you save your money"]),
        Fact(T,
             ["how long to save ten dollars if i get two dollars a week",
              "if i save two dollars a week how long for ten dollars",
              "how many weeks to save ten dollars at two dollars a week",
              "i get two dollars a week when will i have ten dollars"],
             "Count by twos until you reach ten. Two, four, six, eight, ten. That is five hops. So it takes five weeks.",
             ["saving two dollars each week how soon do i reach ten"]),
        Fact(T,
             ["what is a piggy bank for",
              "why do people use a piggy bank",
              "what does a piggy bank do",
              "what goes in a piggy bank"],
             "A piggy bank is a safe spot to keep coins while you save. Because you cannot see inside easily, it is tempting to spend and easier to wait.",
             ["what is the point of a piggy bank"]),
        Fact(T,
             ["what is a bank",
              "what does a bank do with money",
              "why do people keep money in a bank",
              "what is a bank for"],
             "A bank keeps your money safe for you. You can put money in, take money out later, and it is still yours the whole time.",
             ["where do grown ups keep their money safe"]),
        Fact(T,
             ["what is a price tag",
              "what does a price tag tell me",
              "what is the little tag with the number on it",
              "how do i know what something costs in a shop"],
             "A price tag is the little label showing how much a thing costs. Read the number and you know how much money to hand over at the counter.",
             ["how do i find out the cost of something in a store"]),
        Fact(T,
             ["what is a receipt",
              "what does a receipt do",
              "why does the shop give me a piece of paper after paying",
              "what is that paper from the till"],
             "A receipt is a little list of what you bought and what it cost. It proves you paid, and you need it if you want to bring something back.",
             ["what is the paper you get after you buy something"]),
        Fact(T,
             ["what does free mean",
              "what does it mean if something is free",
              "does free mean no money",
              "what is a free thing"],
             "Free means it costs nothing at all. You pay zero, so you can take it without handing over any money.",
             ["how much does a free thing cost"]),
        Fact(T,
             ["what does it mean to spend money",
              "what is spending",
              "what happens when you spend money",
              "what does spending your money mean"],
             "Spending means giving your money away to get something. Once you spend it, that money is gone, so it is worth thinking first about what you really want.",
             ["what does it mean when money is spent"]),
    ]


# --------------------------------------------------------------------------
# sudoku & logic
# --------------------------------------------------------------------------

def _logic():
    T = "sudoku & logic"
    return [
        Fact(T,
             ["what is a puzzle grid",
              "what does a grid mean in a puzzle",
              "what is a grid",
              "explain a puzzle grid to me"],
             "A grid is a box split into little squares, like a window with lots of panes. Puzzle grids have squares you fill in with numbers, letters, or pictures.",
             ["what does a puzzle grid look like"]),
        Fact(T,
             ["what is a row in a grid",
              "what does row mean in a puzzle",
              "which way does a row go",
              "what is a row of squares"],
             "A row goes across from left to right, like a line of writing in a book. In a puzzle you read a row sideways.",
             ["which direction is a row"]),
        Fact(T,
             ["what is a column in a grid",
              "what does column mean in a puzzle",
              "which way does a column go",
              "what is a column of squares"],
             "A column goes up and down, like a tall tower of blocks. In a puzzle you read a column from top to bottom.",
             ["which direction is a column"]),
        Fact(T,
             ["what is the difference between a row and a column",
              "how do i remember row and column",
              "how are rows and columns different",
              "which one is across a row or a column"],
             "A row goes across, like a row of seats in a theater. A column stands up tall, like the stone columns holding up a building.",
             ["is a row the across one or the up and down one"]),
        Fact(T,
             ["what is a box in sudoku",
              "what does box mean in sudoku",
              "what is a sudoku block",
              "what are the smaller squares inside a sudoku grid"],
             "A box is a small square group inside the big grid, marked off with thicker lines. Each box has to hold every number once, just like the rows and columns do.",
             ["what is the thick lined square in sudoku"]),
        Fact(T,
             ["what is sudoku",
              "what is a sudoku puzzle",
              "tell me about sudoku",
              "explain sudoku to me"],
             "Sudoku is a number puzzle on a grid. You fill in the empty squares so that every row, every column, and every box has each number exactly once.",
             ["what kind of puzzle is sudoku"]),
        Fact(T,
             ["what are the rules of sudoku",
              "how do you play sudoku",
              "what do i have to do in sudoku",
              "how does sudoku work"],
             "Fill each empty square with a number. The one rule is no repeats. Every number can show up only once in each row, once in each column, and once in each box.",
             ["what is the main rule in sudoku"]),
        Fact(T,
             ["what is a four by four sudoku",
              "how does a small sudoku work",
              "what numbers go in a four by four sudoku",
              "tell me about a beginner sudoku"],
             "A four by four sudoku uses the numbers one, two, three, and four. Each row, each column, and each little two by two box holds all four numbers once.",
             ["what is the easy small sudoku for kids"]),
        Fact(T,
             ["what is a nine by nine sudoku",
              "how does a big sudoku work",
              "what numbers go in a normal sudoku",
              "tell me about the usual sudoku size"],
             "The usual sudoku is nine squares across and nine down. It uses the numbers one through nine, and each one appears once in every row, column, and box.",
             ["what numbers are used in a regular sudoku"]),
        Fact(T,
             ["why can a number not repeat in a sudoku row",
              "why are repeats not allowed in sudoku",
              "what happens if a number shows up twice in a row",
              "why is repeating a number wrong in sudoku"],
             "Each row has one spot for each number. If a number appears twice, another number has no room left, and the puzzle cannot be finished. So repeats break the puzzle.",
             ["what goes wrong when a number appears twice"]),
        Fact(T,
             ["what does elimination mean in a puzzle",
              "what is reasoning by elimination",
              "how do you solve by elimination",
              "what does it mean to rule things out"],
             "Elimination means crossing off what cannot be true until only one choice is left. If a square cannot be one, two, or four, then it has to be three.",
             ["how does crossing off wrong answers help"]),
        Fact(T,
             ["how do i find the missing number in a row of four",
              "how do i work out which number is missing",
              "a row has one two and four which number is missing",
              "how do i spot the gap in a sudoku row"],
             "Say the numbers you need out loud: one, two, three, four. Check them off against the row. One is there, two is there, four is there, three is not. So the answer is three.",
             ["what number completes a row that has one two and four"]),
        Fact(T,
             ["what is the first thing to do in a sudoku",
              "how should i start a sudoku",
              "where do i begin a sudoku puzzle",
              "what is a good first move in sudoku"],
             "Look for the row, column, or box that is nearly full. With only one gap left, there is only one number it can be, and filling it helps you find the next one.",
             ["which square should i fill in first"]),
        Fact(T,
             ["why is thinking better than guessing in a puzzle",
              "should i guess in sudoku",
              "why should i not guess",
              "is guessing a good way to solve sudoku"],
             "A guess might be wrong, and one wrong number spoils every square after it. If you work it out instead, you know it is right and you never have to start over.",
             ["what is wrong with guessing at a puzzle"]),
        Fact(T,
             ["what should i do if i get stuck on a puzzle",
              "what do i do when a puzzle is too hard",
              "how do i get unstuck in sudoku",
              "what if i cannot find the next number"],
             "Move to a different part of the grid and look there instead. A square you fill in somewhere else often gives you the clue you needed back at the tricky spot.",
             ["what helps when a puzzle feels impossible"]),
        Fact(T,
             ["what are pencil marks in sudoku",
              "why do people write tiny numbers in sudoku squares",
              "what are the little notes in a sudoku square",
              "what is jotting down possible numbers"],
             "Pencil marks are tiny numbers you jot in a square to remember what could still go there. As you learn more, you rub some out until one is left.",
             ["what are the small notes solvers write down"]),
        Fact(T,
             ["how do i check my sudoku is right",
              "how do i know i solved the puzzle",
              "how can i check my puzzle answers",
              "what do i do at the end of a sudoku"],
             "Read each row and make sure every number is there once. Then do the same for each column and each box. If nothing repeats and nothing is missing, you solved it.",
             ["how do i make sure a finished sudoku is correct"]),
        Fact(T,
             ["what is logic",
              "what does logic mean",
              "what is logical thinking",
              "explain logic to me"],
             "Logic is careful step by step thinking. You start with what you know for sure, and each step leads to the next, until the answer has to be true.",
             ["what does it mean to think logically"]),
        Fact(T,
             ["what is a clue in a puzzle",
              "what does clue mean",
              "what do clues do in a puzzle",
              "why do puzzles give clues"],
             "A clue is a piece of information you are given for free. Clues are the true facts you start from, and good thinking turns them into the rest of the answer.",
             ["what is the point of a puzzle clue"]),
        Fact(T,
             ["what does if this then that mean in logic",
              "how do if then sentences work",
              "what is an if then rule",
              "how does one fact lead to another"],
             "An if then rule links two facts. If it is raining then the ground is wet. Once you know the first part is true, you know the second part must be true too.",
             ["how do you use an if then clue"]),
        Fact(T,
             ["how do i solve an odd one out puzzle",
              "what is an odd one out puzzle",
              "how do i find the odd one out",
              "what do i look for in odd one out"],
             "Look for the thing all but one share. If a cat, dog, horse, and chair are listed, three are animals and one is furniture. So the chair is the odd one out.",
             ["how do i spot which one does not belong"]),
        Fact(T,
             ["how do i find the pattern in a number sequence",
              "how do patterns in puzzles work",
              "what is the next number puzzle about",
              "how do i work out what comes next"],
             "Look at how each number changes into the next one. In two, four, six, eight, each step adds two. Keep adding two and the next number is ten.",
             ["what comes after two four six eight and why"]),
        Fact(T,
             ["why are puzzles good for you",
              "why should i do puzzles",
              "what do puzzles teach you",
              "are puzzles good for my brain"],
             "Puzzles give your brain practice at being patient and careful. The same steady thinking helps with math homework and with figuring out tricky problems in real life.",
             ["what is the point of doing puzzles"]),
        # Mazes are owned by games_board.py. This module used to answer the
        # same questions with a different trick - "start at the finish and
        # trace backward, because there are fewer wrong turns that way" - and
        # that justification is not generally true. Two modules answering
        # "what is a maze" differently teaches the model a contradiction, so
        # the topic lives in exactly one place.
        Fact(T,
             ["does every sudoku have only one answer",
              "can a sudoku have two answers",
              "is there just one solution to a sudoku",
              "how many answers does a sudoku have"],
             "A proper sudoku has exactly one solution. That is why you never have to guess, because careful thinking can always find the one right answer.",
             ["is there more than one way to finish a sudoku"]),
    ]


# --------------------------------------------------------------------------
# telling time
# --------------------------------------------------------------------------

def _time():
    T = "telling time"
    return [
        Fact(T,
             ["what are the hands on a clock",
              "what are clock hands",
              "how many hands does a clock have",
              "what do the pointers on a clock do"],
             "A clock has a short hand and a long hand. The short one points at the hour and the long one points at the minutes. Some clocks add a thin hand for seconds.",
             ["what are the pointy bits on a clock face"]),
        Fact(T,
             ["which hand is the hour hand",
              "how do i know which is the hour hand",
              "what does the short hand on a clock do",
              "which clock hand shows the hour"],
             "The hour hand is the short fat one. It moves very slowly and points at the hour number. Short hand, short word, hour.",
             ["what does the little hand on a clock mean"]),
        Fact(T,
             ["which hand is the minute hand",
              "how do i know which is the minute hand",
              "what does the long hand on a clock do",
              "which clock hand shows the minutes"],
             "The minute hand is the long thin one. It travels all the way around the clock face once every hour, counting the minutes as it goes.",
             ["what does the big hand on a clock mean"]),
        Fact(T,
             ["what does o clock mean",
              "what does it mean when we say o clock",
              "when do you say o clock",
              "what is o clock on a clock"],
             "O clock means an exact hour with no extra minutes. The long hand points straight up at twelve, and the short hand points at the hour.",
             ["what does the clock look like at o clock"]),
        Fact(T,
             ["what does half past mean",
              "what is half past on a clock",
              "when do you say half past",
              "what does half past look like"],
             "Half past means half an hour after the hour, which is thirty minutes. The long hand points straight down at six, halfway around the clock face.",
             ["where is the big hand at half past"]),
        Fact(T,
             ["what does quarter past mean",
              "what is quarter past on a clock",
              "when do you say quarter past",
              "what does quarter past look like"],
             "Quarter past means fifteen minutes after the hour, because fifteen is a quarter of sixty. The long hand points right at three, a quarter of the way around.",
             ["where is the big hand at quarter past"]),
        Fact(T,
             ["what does quarter to mean",
              "what is quarter to on a clock",
              "when do you say quarter to",
              "what does quarter to look like"],
             "Quarter to means fifteen minutes before the next hour. The long hand points left at nine, with just a quarter of the circle left to go.",
             ["where is the big hand at quarter to"]),
        Fact(T,
             ["why is fifteen minutes called a quarter of an hour",
              "why do we say a quarter of an hour",
              "how is fifteen minutes a quarter",
              "why is quarter past fifteen minutes"],
             "An hour is sixty minutes. Sixty splits into four equal parts of fifteen. So fifteen minutes is one quarter of an hour.",
             ["how many minutes make a quarter of an hour"]),
        Fact(T,
             ["how many minutes are in half an hour",
              "how long is half an hour",
              "what is half an hour in minutes",
              "how many minutes make half an hour"],
             "An hour is sixty minutes. Half of sixty is thirty, because sixty splits into thirty and thirty. So half an hour is thirty minutes.",
             ["half an hour is how many minutes"]),
        Fact(T,
             ["how many minutes are in three quarters of an hour",
              "how long is three quarters of an hour",
              "what is three quarters of an hour in minutes",
              "how many minutes make three quarters of an hour"],
             "A quarter of an hour is fifteen minutes. Three quarters is fifteen and fifteen and fifteen, which is forty-five. So it is forty-five minutes.",
             ["three quarters of an hour is how many minutes"]),
        Fact(T,
             ["how many seconds are in a minute",
              "how long is a minute in seconds",
              "how many seconds make one minute",
              "what is a minute in seconds"],
             "One minute is sixty seconds. If you count slowly all the way to sixty, a whole minute has gone by.",
             ["a minute is how many seconds"]),
        Fact(T,
             ["how many minutes are in an hour",
              "how long is an hour in minutes",
              "how many minutes make one hour",
              "what is an hour in minutes"],
             "One hour is sixty minutes. That is the long hand going all the way around the clock face one time.",
             ["an hour is how many minutes"]),
        Fact(T,
             ["how many hours are in a day",
              "how long is a day in hours",
              "how many hours make one day",
              "what is a day in hours"],
             "One day is twenty-four hours. That is twelve hours shown on the clock face twice, once for the morning and once for the afternoon and night.",
             ["a day is how many hours"]),
        Fact(T,
             ["how many seconds are in an hour",
              "how many seconds make one hour",
              "what is an hour in seconds",
              "how long is an hour in seconds"],
             "An hour is sixty minutes and each minute is sixty seconds. Sixty lots of sixty is three thousand six hundred. So an hour is three thousand six hundred seconds.",
             ["an hour is how many seconds"]),
        Fact(T,
             ["how many days are in a week",
              "how many days make one week",
              "what is a week in days",
              "how long is a week"],
             "One week is seven days. They are Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, and Saturday.",
             ["a week is how many days"]),
        Fact(T,
             ["what are the days of the week",
              "can you name the days of the week",
              "list the days of the week",
              "tell me all the days of the week"],
             "The days are Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, and Saturday. Saturday and Sunday together are called the weekend.",
             ["say the seven day names for me"]),
        Fact(T,
             ["what are the months of the year",
              "can you name the months",
              "list the months of the year",
              "tell me all the months"],
             "January, February, March, April, May, June, July, August, September, October, November, and December.",
             ["say all the month names for me"]),
        Fact(T,
             ["how many months are in a year",
              "how many months make one year",
              "what is a year in months",
              "how long is a year in months"],
             "One year is twelve months, starting with January and ending with December.",
             ["a year is how many months"]),
        Fact(T,
             ["how many days are in a year",
              "how many days make one year",
              "what is a year in days",
              "how long is a year in days"],
             "A year is three hundred and sixty-five days. Every fourth year gets one extra day and has three hundred and sixty-six.",
             ["a year is how many days"]),
        Fact(T,
             ["how many weeks are in a year",
              "how many weeks make one year",
              "what is a year in weeks",
              "roughly how many weeks in a year"],
             "A year has fifty-two weeks with a day or two left over. Fifty-two weeks of seven days is three hundred and sixty-four, and a year is three hundred and sixty-five days.",
             ["a year is about how many weeks"]),
        Fact(T,
             ["what is a leap year",
              "why do we have a leap year",
              "what happens in a leap year",
              "what is the extra day in february"],
             "A leap year comes every fourth year and has one extra day, the twenty-ninth of February. It keeps our calendar lined up with the sun.",
             ["why does february sometimes get an extra day"]),
        Fact(T,
             ["what does am mean",
              "what is am on a clock",
              "when is it am",
              "what does the am on a clock mean"],
             "A m means the morning half of the day, from midnight until noon. Breakfast time and the start of school are a m.",
             ["which part of the day is am"]),
        Fact(T,
             ["what does pm mean",
              "what is pm on a clock",
              "when is it pm",
              "what does the pm on a clock mean"],
             "P m means the afternoon and night half of the day, from noon until midnight. Dinner and bedtime are p m.",
             ["which part of the day is pm"]),
        Fact(T,
             ["why do we need am and pm",
              "why are there two sets of hours in a day",
              "why does the clock show each hour twice",
              "what is am and pm for"],
             "A clock face only counts to twelve, but a day has twenty-four hours. A m and p m tell you which time round it is, so nine in the morning is not mixed up with nine at night.",
             ["why do clocks repeat the same numbers twice a day"]),
        Fact(T,
             ["what is noon",
              "what does midday mean",
              "when is noon",
              "what time is midday"],
             "Noon is twelve o clock in the middle of the day, usually around lunchtime. It is the moment the morning ends and the afternoon begins.",
             ["what time of day is noon"]),
        Fact(T,
             ["what is midnight",
              "when is midnight",
              "what time is midnight",
              "what does midnight mean"],
             "Midnight is twelve o clock in the middle of the night, when most people are fast asleep. It is the moment one day ends and the next one starts.",
             ["what time of night is midnight"]),
        Fact(T,
             ["how do i read a digital clock",
              "what do the numbers on a digital clock mean",
              "how does a digital clock work",
              "how do i tell time on a digital clock"],
             "A digital clock shows two numbers with dots between them. The one on the left is the hour and the one on the right is how many minutes past that hour.",
             ["what are the two numbers on a digital clock"]),
        Fact(T,
             ["what does the clock look like at half past three",
              "where are the hands at half past three",
              "how do i show half past three on a clock",
              "what do the hands do at half past three"],
             "Half past means thirty minutes, so the long hand points straight down at six. The short hand sits halfway between three and four. That is half past three.",
             ["show me half past three on a clock face"]),
        Fact(T,
             ["what does the clock look like at quarter past seven",
              "where are the hands at quarter past seven",
              "how do i show quarter past seven on a clock",
              "what do the hands do at quarter past seven"],
             "Quarter past means fifteen minutes, so the long hand points right at three. The short hand has just gone past seven. That is quarter past seven.",
             ["show me quarter past seven on a clock face"]),
        Fact(T,
             ["what does the clock look like at quarter to five",
              "where are the hands at quarter to five",
              "how do i show quarter to five on a clock",
              "what do the hands do at quarter to five"],
             "Quarter to means fifteen minutes before the hour, so the long hand points left at nine. The short hand is nearly at five. That is quarter to five.",
             ["show me quarter to five on a clock face"]),
        Fact(T,
             ["if it is three o clock what time is it in two hours",
              "what is two hours after three o clock",
              "three o clock plus two hours is what time",
              "add two hours to three o clock"],
             "Start at three and count on two hours. Four, then five. So two hours after three o clock is five o clock.",
             ["what time comes two hours after three o clock"]),
        Fact(T,
             ["if it is six o clock what time is it in three hours",
              "what is three hours after six o clock",
              "six o clock plus three hours is what time",
              "add three hours to six o clock"],
             "Start at six and count on three hours. Seven, eight, nine. So three hours after six o clock is nine o clock.",
             ["what time comes three hours after six o clock"]),
        Fact(T,
             ["if it is two o clock what time is it in thirty minutes",
              "what is thirty minutes after two o clock",
              "two o clock plus half an hour is what time",
              "add half an hour to two o clock"],
             "Thirty minutes is half an hour. Half an hour after two o clock lands you at half past two.",
             ["what time comes half an hour after two o clock"]),
        Fact(T,
             ["how long from two o clock to five o clock",
              "how many hours between two o clock and five o clock",
              "what is the time from two o clock until five o clock",
              "how long is it from two until five"],
             "Count on from two until you reach five. Three, four, five. That is three hops of one hour each. So it is three hours.",
             ["how many hours pass between two and five o clock"]),
        Fact(T,
             ["how long from nine o clock to twelve o clock",
              "how many hours between nine o clock and twelve o clock",
              "what is the time from nine o clock until twelve o clock",
              "how long is it from nine until twelve"],
             "Count on from nine until you reach twelve. Ten, eleven, twelve. That is three hops of one hour each. So it is three hours.",
             ["how many hours pass between nine and twelve o clock"]),
        Fact(T,
             ["how long does it take to brush your teeth",
              "how long should i brush my teeth",
              "how many minutes for brushing teeth",
              "how long is tooth brushing supposed to be"],
             "You should brush for two minutes. Two minutes is one hundred and twenty seconds, because sixty and sixty is one hundred and twenty.",
             ["how many minutes of tooth brushing is right"]),
        Fact(T,
             ["how long is a school day",
              "how many hours is school",
              "how long do kids spend at school",
              "how much of the day is school"],
             "A school day is usually about six hours long, plus a break for lunch. That is a quarter of the whole twenty-four hour day.",
             ["how many hours do you spend at school"]),
        Fact(T,
             ["how long should kids sleep",
              "how many hours of sleep do children need",
              "how much sleep does a kid need",
              "how long is a good night's sleep for a child"],
             "Children need about ten to eleven hours of sleep. If you go to bed at eight in the evening and get up at seven, that is eleven hours.",
             ["how many hours should a child sleep each night"]),
        Fact(T,
             ["how long does it take to boil an egg",
              "how many minutes to boil an egg",
              "how long do you cook a boiled egg",
              "how long is an egg in the water for"],
             "A soft boiled egg takes about three minutes and a hard boiled one takes about ten. Three minutes is one hundred and eighty seconds.",
             ["how many minutes for a boiled egg"]),
        Fact(T,
             ["what is a calendar",
              "what does a calendar do",
              "what is a calendar for",
              "why do people have calendars"],
             "A calendar is a chart of all the days in a month or a year. It helps you see what day today is and count how many sleeps until something special.",
             ["what does a calendar show you"]),
        Fact(T,
             ["how do i count days on a calendar",
              "how do i work out how many days until something",
              "how do i count sleeps until my birthday",
              "how can a calendar tell me how long to wait"],
             "Put a finger on today and hop forward one square for each day, counting as you go, until you reach the special day. The number of hops is how many days to wait.",
             ["how do i count forward to a date"]),
        Fact(T,
             ["what is a weekend",
              "which days are the weekend",
              "what does weekend mean",
              "when is the weekend"],
             "The weekend is Saturday and Sunday, the two days at the end of the week. Most schools are closed then, so it is a time for resting and playing.",
             ["which two days make the weekend"]),
        Fact(T,
             ["what does yesterday mean",
              "what is yesterday",
              "which day is yesterday",
              "when was yesterday"],
             "Yesterday is the day before today. If today is Tuesday, then yesterday was Monday.",
             ["if today is tuesday what was yesterday"]),
        Fact(T,
             ["what does tomorrow mean",
              "what is tomorrow",
              "which day is tomorrow",
              "when is tomorrow"],
             "Tomorrow is the day after today. If today is Tuesday, then tomorrow will be Wednesday.",
             ["if today is tuesday what is tomorrow"]),
        Fact(T,
             ["what is the difference between a second and a minute",
              "which is longer a second or a minute",
              "is a minute longer than a second",
              "how much bigger is a minute than a second"],
             "A second is one quick tick, about as long as saying one elephant. A minute is sixty of those ticks, so a minute is much longer.",
             ["which lasts longer one second or one minute"]),
        Fact(T,
             ["which is longer an hour or a day",
              "is a day longer than an hour",
              "what is the difference between an hour and a day",
              "how much bigger is a day than an hour"],
             "A day holds twenty-four hours inside it. So a day is much longer than an hour, twenty-four times longer.",
             ["how many hours fit inside one day"]),
        Fact(T,
             ["what is a timer for",
              "why do people use a timer",
              "what does a timer do",
              "when would i use a timer"],
             "A timer counts down and beeps when the time is up. People use one for cooking, for brushing teeth, and for taking turns at a game.",
             ["what is the point of setting a timer"]),
        Fact(T,
             ["why does a clock face only go to twelve",
              "why are there twelve numbers on a clock",
              "why does a clock stop at twelve",
              "why not twenty four numbers on a clock"],
             "Twelve numbers fit neatly around the circle and are easy to read. The hour hand goes around twice in a day, and twelve and twelve make the full twenty-four hours.",
             ["why are there only twelve numbers around a clock"]),
    ]


def build():
    return (_fractions() + _percentages() + _roman() + _money()
            + _logic() + _time())


if __name__ == "__main__":
    from tools.braino.facts import report
    report("mathconcepts", build())
