"""Convert the Braino AI logo (black line art on white) into 4-bit alpha masks.

  python tools/gen_logo.py assets/braino_logo.png main/logo_data.h

Outputs two masks (coverage 0..15, two pixels per byte, row-major):
  logo_full  : the whole logo (bulb + brain + "Braino AI" wordmark), for the
               boot welcome screen
  logo_brain : just the brain (top part of the bulb, no "TM"), for the header

The device tints them (Claude orange on black) with anti-aliased edges.
"""
import sys

from PIL import Image, ImageOps

FULL_H = 230        # welcome screen logo height (px)
BRAIN_H = 28        # header icon height (px): exactly two text rows


def ink_mask(img):
    """Grayscale ink coverage: 255 = black ink, 0 = white paper."""
    # Transparent PNGs: composite onto white paper first.
    rgba = img.convert("RGBA")
    paper = Image.new("RGBA", rgba.size, (255, 255, 255, 255))
    g = ImageOps.grayscale(Image.alpha_composite(paper, rgba).convert("RGB"))
    return ImageOps.invert(g)


def bbox_of(mask, box=None, thresh=96):
    m = mask.crop(box) if box else mask
    bw = m.point(lambda v: 255 if v > thresh else 0)
    bb = bw.getbbox()
    if box and bb:
        bb = (bb[0] + box[0], bb[1] + box[1], bb[2] + box[0], bb[3] + box[1])
    return bb


def to4bit(mask, name):
    w, h = mask.size
    px = mask.load()
    out = []
    for y in range(h):
        row = []
        for x in range(0, w, 2):
            a = px[x, y] >> 4
            b = (px[x + 1, y] >> 4) if x + 1 < w else 0
            row.append((a << 4) | b)
        out.extend(row)
    lines = [f"#define {name.upper()}_W {w}", f"#define {name.upper()}_H {h}",
             f"static const uint8_t {name}[{len(out)}] = {{"]
    for i in range(0, len(out), 24):
        lines.append("    " + ",".join(f"0x{v:02X}" for v in out[i:i + 24]) + ",")
    lines.append("};")
    return "\n".join(lines)


def fit(mask, box, height):
    crop = mask.crop(box)
    w = max(2, round(crop.width * height / crop.height))
    return crop.resize((w, height), Image.LANCZOS)


def main():
    src, dst = sys.argv[1], sys.argv[2]
    img = Image.open(src)
    ink = ink_mask(img)
    W, H = ink.size

    full = bbox_of(ink)
    # Brain: the top part of the drawing, above the bulb neck. Find the first
    # row (from the top of the drawing) where the ink narrows sharply: the
    # neck. Fallback: top 58% of the drawing height.
    x0, y0, x1, y1 = full
    fw, fh = x1 - x0, y1 - y0
    # Brain = the bulb's head, down to the neck (above the screw lines).
    brain_bottom = y0 + int(fh * 0.62)
    # The "TM" mark sits alone in the top-right corner, above the right lobe:
    # blank that corner before measuring the brain.
    no_tm = ink.copy()
    no_tm.paste(0, (x0 + int(fw * 0.82), y0, x1, y0 + int(fh * 0.07)))
    brain = bbox_of(no_tm, (x0, y0, x1, brain_bottom))
    ink_brain = no_tm

    full_m = fit(ink, full, FULL_H)
    brain_m = fit(ink_brain, brain, BRAIN_H)
    with open(dst, "w", encoding="ascii") as f:
        f.write("// Generated by tools/gen_logo.py from the Braino AI logo. Do not edit.\n")
        f.write("// 4-bit ink coverage masks, two pixels per byte (high nibble first).\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(to4bit(full_m, "logo_full") + "\n\n")
        f.write(to4bit(brain_m, "logo_brain") + "\n")
    prev = "models_out/ui/logo"
    full_m.save(prev + "_full_preview.png")
    brain_m.resize((brain_m.width * 4, brain_m.height * 4), Image.NEAREST).save(
        prev + "_brain_preview.png")
    print(f"full {full_m.size} from {full}, brain {brain_m.size} from {brain} (source {W}x{H})")


if __name__ == "__main__":
    main()
