"""Convert an X11 misc-fixed BDF font (public domain) to a C header.

Usage: python tools/gen_font.py 8x13.bdf components/story_ui/font_8x13.h font8x13

Emits printable ASCII 0x20..0x7E as one byte per row (fonts up to 8 px wide),
MSB = leftmost pixel, rows padded to the font bounding box.
"""
import sys


def parse(path):
    lines = open(path, encoding="latin-1").read().splitlines()
    bbx_w = bbx_h = bbx_x = bbx_y = 0
    glyphs = {}
    i = 0
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("FONTBOUNDINGBOX"):
            bbx_w, bbx_h, bbx_x, bbx_y = map(int, ln.split()[1:])
        if ln.startswith("STARTCHAR"):
            enc = None
            gb = None
            j = i + 1
            while not lines[j].startswith("BITMAP"):
                if lines[j].startswith("ENCODING"):
                    enc = int(lines[j].split()[1])
                if lines[j].startswith("BBX"):
                    gb = tuple(map(int, lines[j].split()[1:]))
                j += 1
            rows = []
            j += 1
            while not lines[j].startswith("ENDCHAR"):
                rows.append(int(lines[j], 16))
                j += 1
            if enc is not None and 0x20 <= enc <= 0x7E:
                glyphs[enc] = (gb, rows)
            i = j
        i += 1
    return (bbx_w, bbx_h, bbx_x, bbx_y), glyphs


def main():
    src, dst, name = sys.argv[1:4]
    (W, H, X0, Y0), glyphs = parse(src)
    assert W <= 8, "only fonts up to 8 px wide"
    out = []
    for code in range(0x20, 0x7F):
        cell = [0] * H
        if code in glyphs:
            (gw, gh, gx, gy), rows = glyphs[code]
            nbytes = (gw + 7) // 8
            top = (H + Y0) - (gy + gh)  # rows from cell top to glyph top
            for r, v in enumerate(rows):
                v >>= (nbytes * 8 - 8) if nbytes > 1 else 0
                shift = gx - X0
                v = (v >> shift) & 0xFF
                y = top + r
                if 0 <= y < H:
                    cell[y] = v
        out.append(cell)
    with open(dst, "w") as f:
        f.write(f"// Generated by tools/gen_font.py from X11 misc-fixed {src.split('/')[-1]} (public domain).\n")
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write(f"#define {name.upper()}_W {W}\n#define {name.upper()}_H {H}\n")
        f.write(f"static const uint8_t {name}[95][{H}] = {{\n")
        for code, cell in zip(range(0x20, 0x7F), out):
            ch = chr(code).replace("\\", "backslash")
            f.write("    {" + ",".join(f"0x{b:02X}" for b in cell) + f"}}, // '{ch}'\n")
        f.write("};\n")


if __name__ == "__main__":
    main()
