"""Render the Ivy AI logo (SVG) into RGB565 images for the display.

  python tools/gen_logo.py assets/ivy_ai_logo.svg main/logo_data.h

The SVG is rasterised by a headless Chrome/Edge at 4x, composited on black
(the screen background), then downscaled with Lanczos. Outputs:
  logo_full : leaf + "Ivy AI" wordmark, for the boot welcome screen
  logo_icon : just the leaf symbol, for the header

The wordmark's dark "Ivy" is recoloured light so it reads on black.
"""
import os
import re
import shutil
import subprocess
import sys
import tempfile

from PIL import Image

FULL_H = 230        # welcome screen logo height (px)
ICON_H = 28         # header icon height (px): exactly two text rows
SCALE = 4           # render oversampling
IVY_ON_BLACK = "#f3e6de"

BROWSERS = [
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    "google-chrome", "chromium", "msedge",
]


def browser():
    for b in BROWSERS:
        if os.path.exists(b) or shutil.which(b):
            return b
    sys.exit("gen_logo: need Chrome or Edge to rasterise the SVG")


def variant(svg, symbol_only):
    s = svg.replace("fill:#3b2520", "fill:" + IVY_ON_BLACK)
    if symbol_only:
        s = re.sub(r'<g\s+id="wordmark".*(?=</svg>)', "", s, flags=re.S)   # wordmark is the last group
    w, h = 520 * SCALE, 620 * SCALE
    s = re.sub(r'width="520"\s+height="620"', f'width="{w}" height="{h}"', s, count=1)
    # Black paper under everything.
    return s.replace("</defs>", '</defs><rect width="520" height="620" fill="#000"/>', 1), w, h


def rasterise(svg_text, w, h, tmp, name):
    src = os.path.join(tmp, name + ".svg")
    png = os.path.join(tmp, name + ".png")
    with open(src, "w", encoding="utf-8") as f:
        f.write(svg_text)
    subprocess.run([browser(), "--headless", "--disable-gpu", "--hide-scrollbars",
                    f"--window-size={w},{h}", f"--screenshot={png}",
                    "file:///" + src.replace("\\", "/")],
                   check=True, capture_output=True, timeout=60)
    return Image.open(png).convert("RGB").crop((0, 0, w, h))


def fit(img, height):
    lum = img.convert("L").point(lambda v: 255 if v > 12 else 0)
    crop = img.crop(lum.getbbox())
    w = max(2, round(crop.width * height / crop.height))
    return crop.resize((w, height), Image.LANCZOS)


def to565(img, name):
    w, h = img.size
    px = img.load()
    out = []
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            out.append(((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3))
    lines = [f"#define {name.upper()}_W {w}", f"#define {name.upper()}_H {h}",
             f"static const uint16_t {name}[{len(out)}] = {{"]
    for i in range(0, len(out), 16):
        lines.append("    " + ",".join(f"0x{v:04X}" for v in out[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    src, dst = sys.argv[1], sys.argv[2]
    svg = open(src, encoding="utf-8").read()
    with tempfile.TemporaryDirectory() as tmp:
        full = fit(rasterise(*variant(svg, False), tmp, "full"), FULL_H)
        icon = fit(rasterise(*variant(svg, True), tmp, "icon"), ICON_H)
    with open(dst, "w", encoding="ascii") as f:
        f.write("// Generated by tools/gen_logo.py from assets/ivy_ai_logo.svg. Do not edit.\n")
        f.write("// RGB565 pixels on black, row-major.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(to565(full, "logo_full") + "\n\n")
        f.write(to565(icon, "logo_icon") + "\n")
    os.makedirs("models_out/ui", exist_ok=True)
    full.save("models_out/ui/logo_full_preview.png")
    icon.resize((icon.width * 4, icon.height * 4), Image.NEAREST).save("models_out/ui/logo_icon_preview.png")
    print(f"full {full.size}, icon {icon.size}")


if __name__ == "__main__":
    main()
