"""Convert an X11 misc-fixed BDF font (public domain) to a C header.

Usage: python tools/gen_font.py 8x13.bdf components/story_ui/font_8x13.h font8x13

Emits printable ASCII 0x20..0x7E, then extra UI glyphs at byte codes 0x80..
(box drawing, bullet, CLI-style spinner). Glyphs missing from the BDF (the
spinner stars) are hand-drawn below. One byte per row, MSB = leftmost pixel.
"""
import sys

# (byte code, name, unicode codepoint or None, hand-drawn rows if None)
# Hand-drawn rows are listed for rows 0..12 (13-pixel cell).
EXTRAS = [
    (0x80, "BOX_TL", 0x256D, None),   # rounded corner top-left
    (0x81, "BOX_TR", 0x256E, None),
    (0x82, "BOX_BL", 0x2570, None),
    (0x83, "BOX_BR", 0x256F, None),
    (0x84, "BOX_H", 0x2500, None),
    (0x85, "BOX_V", 0x2502, None),
    (0x86, "BULLET", 0x25CF, None),   # answer bullet
    (0x87, "RESULT", 0x23BF, None),   # result/detail elbow
    (0x88, "MIDDOT", 0x00B7, None),
    (0x89, "ELLIPSIS", 0x2026, None),
    # CLI-style spinner frames: dot, small plus, 6-point star, 8-point star
    (0x8A, "SPIN0", None, [0, 0, 0, 0, 0, 0x18, 0x18, 0, 0, 0, 0, 0, 0]),
    (0x8B, "SPIN1", None, [0, 0, 0, 0, 0x10, 0x10, 0x7C, 0x10, 0x10, 0, 0, 0, 0]),
    (0x8C, "SPIN2", None, [0, 0, 0, 0x10, 0x54, 0x38, 0xFE, 0x38, 0x54, 0x10, 0, 0, 0]),
    (0x8D, "SPIN3", None, [0, 0, 0, 0x10, 0x92, 0x54, 0x38, 0xFE, 0x38, 0x54, 0x92, 0x10, 0]),
]


def parse(path):
    lines = open(path, encoding="latin-1").read().splitlines()
    bbx = (0, 0, 0, 0)
    glyphs = {}
    i = 0
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("FONTBOUNDINGBOX"):
            bbx = tuple(map(int, ln.split()[1:]))
        if ln.startswith("STARTCHAR"):
            enc = gb = None
            j = i + 1
            while not lines[j].startswith("BITMAP"):
                if lines[j].startswith("ENCODING"):
                    enc = int(lines[j].split()[1])
                if lines[j].startswith("BBX"):
                    gb = tuple(map(int, lines[j].split()[1:]))
                j += 1
            rows = []
            j += 1
            while not lines[j].startswith("ENDCHAR"):
                rows.append(int(lines[j], 16))
                j += 1
            if enc is not None:
                glyphs[enc] = (gb, rows)
            i = j
        i += 1
    return bbx, glyphs


def render(bbx, glyph):
    W, H, X0, Y0 = bbx
    cell = [0] * H
    if glyph is None:
        return cell
    (gw, gh, gx, gy), rows = glyph
    nbytes = (gw + 7) // 8
    top = (H + Y0) - (gy + gh)
    for r, v in enumerate(rows):
        if nbytes > 1:
            v >>= nbytes * 8 - 8
        v = (v >> (gx - X0)) & 0xFF
        y = top + r
        if 0 <= y < H:
            cell[y] = v
    return cell


def main():
    src, dst, name = sys.argv[1:4]
    bbx, glyphs = parse(src)
    W, H = bbx[0], bbx[1]
    assert W <= 8, "only fonts up to 8 px wide"
    with open(dst, "w", encoding="ascii") as f:
        f.write(f"// Generated by tools/gen_font.py from X11 misc-fixed {src.replace(chr(92), '/').split('/')[-1]}"
                " (public domain) + hand-drawn spinner glyphs.\n")
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write(f"#define {name.upper()}_W {W}\n#define {name.upper()}_H {H}\n")
        f.write(f"static const uint8_t {name}[95][{H}] = {{\n")
        for code in range(0x20, 0x7F):
            cell = render(bbx, glyphs.get(code))
            ch = chr(code).replace("\\", "backslash")
            f.write("    {" + ",".join(f"0x{b:02X}" for b in cell) + f"}}, // '{ch}'\n")
        f.write("};\n\n")
        f.write(f"#define {name.upper()}_EXTRA_FIRST 0x{EXTRAS[0][0]:02X}\n")
        f.write(f"#define {name.upper()}_EXTRA_COUNT {len(EXTRAS)}\n")
        f.write(f"static const uint8_t {name}_extra[{len(EXTRAS)}][{H}] = {{\n")
        for code, nm, cp, rows in EXTRAS:
            if cp is not None:
                if cp not in glyphs:
                    raise SystemExit(f"glyph U+{cp:04X} missing from {src}")
                cell = render(bbx, glyphs[cp])
            else:
                cell = (rows + [0] * H)[:H]
            f.write("    {" + ",".join(f"0x{b:02X}" for b in cell) + f"}}, // 0x{code:02X} {nm}\n")
        f.write("};\n")


if __name__ == "__main__":
    main()
